orchest/orchest

orchest/orchest-api/Dockerfile_celery, orchest/orchest-api/Dockerfile_celery.dockerignore, orchest/orchest-api/app/app/apis/namespace_experiments.py, orchest/orchest-api/app/config.py, orchest/orchest-api/start_celery_workers.sh, orchest/orchest-ctl/app/main.py
Experiments now run sequentially but in parallel with interactive pipeline runs. Thus you can always interactively run a pipeline.
Additionally, celery tasks (for experiments) are now persisted to disk.
=> Add configurations for Celery w.r.t. experiments

services/orchest-api/app/app/apis/namespace_experiments.py, services/orchest-api/app/app/models.py, services/orchest-api/app/app/schema.py
Add `total_number_of_pipeline_runs` and `completed_pipeline_runs` attributes to the `Experiment` schema.
=> Add status indication for experiments

services/orchest-webserver/app/app/config.py, services/orchest-webserver/app/app/views/core.py
improvements to project initialization
Creating a project through the GUI, importing a project through the GUI, creating a directory
in userdir/projects or cloning into userdir/projects will use the same function to initialize the project.
Initializing a project means checking that the correct directory and files are presents, like the .orchest directory or its content, and
creating them when they are not, after that environments are built and kernels refreshed.
=> improvements to project initialization

lib/javascript/utils/all.js, services/orchest-webserver/app/static/css/main.scss, services/orchest-webserver/app/static/image/cross-fill.svg, services/orchest-webserver/app/static/js/components/PipelineStep.js, services/orchest-webserver/app/static/js/utils/webserver-utils.js, services/orchest-webserver/app/static/js/views/EnvironmentEditView.js, services/orchest-webserver/app/static/js/views/PipelineView.js
This PR introduces a cool new feature to Orchest: the ability to zoom around in the pipeline editor.
Initial version has been tested, but further cross-device testing seems necessary given intricacies of scroll-wheel mouse events.
In this PR two GUI elements (- and + buttons) are added and the behavior of the center button now includes resetting zoom scale to 1.
=> Introduce zoom for the Pipeline editor/viewer

lib/python/orchest-internals/_orchest/internals/utils.py, services/orchest-api/app/app/apis/namespace_environment_images.py, services/orchest-api/app/app/core/environment_builds.py
By default the Docker SDK for Python suffers from a race condition when calling client.images.list(). As one of the images retrieved by the loop could be missing, in which case it throws an exception:
https://github.com/docker/docker-py/blob/master/docker/models/images.py
This PR wraps the list function to avoid the issue by retrying on failure.
=> Wrap docker sdk images.list with internal util function

services/orchest-api/app/app/apis/namespace_experiments.py, services/orchest-api/app/app/apis/namespace_runs.py, services/orchest-api/app/app/core/environment_builds.py, services/orchest-webserver/app/static/js/utils/webserver-utils.js, services/orchest-webserver/app/static/js/views/CreateExperimentView.js, services/orchest-webserver/app/static/js/views/PipelineView.js
This PR is a minor refactor of the API endpoints for POSTing interactive runs and experiments. 
It improves logging and storing to db in the case of a failure that made it impossible to start a run (interactive or belonging to an experiment) through the request.
Moreover, it delivers an improved experience in the case a user is actually able to start an interactive run through the GUI when a docker image which is a dependency of the pipeline has been deleted. The GUI will now correctly display a failure and the right button(s), e.g. the run won't be stuck in a permanent pending (and cancelable) state anymore.
=> Improve InteractiveRun and Experiment POST endpoints

services/orchest-api/app/app/core/sessions.py, services/orchest-api/app/app/utils.py
Overallocating by a fraction instead of a fixed size to increase the probability with which the user gets exactly the requested size for the memory server.
=> Fix memory server allocation

orchest-sdk/python/orchest/transfer.py, orchest-sdk/python/requirements.txt, orchest-sdk/python/setup.py, orchest-sdk/python/tests/test_transfer.py, services/memory-server/requirements-dev.txt, services/memory-server/requirements.txt
This PR aims to remove references to `pyarrow.serialize` and `pyarrow.deserialize` since they are
deprecated.
It improves data serialization by avoiding an unnecessary serialization that was previously
done to pickles.
Getting data from memory and disk has been made more efficient by avoiding unnecessary
copies of in-memory data.
=> Remove deprecated pyarrow.serialize/deserialize calls, make memory passing more efficient.

services/base-images/runnable-shared/runner/runner/preprocessors.py, services/base-images/runnable-shared/runner/runner/runners.py, services/orchest-api/app/app/core/pipelines.py, services/orchest-webserver/app/static/css/main.scss, services/orchest-webserver/app/static/js/jupyter/Jupyter.js, services/orchest-webserver/app/static/js/utils/webserver-utils.js, services/orchest-webserver/app/static/js/views/FilePreviewView.js, services/orchest-webserver/app/static/js/views/PipelineSettingsView.js, services/orchest-webserver/app/static/js/views/PipelineView.js
This PR introduces the ability to navigate the file viewer through the parent/child steps connected to the file being viewed.
In addition, notebooks will now be serialized to disk when a cell is executed such that notebook outputs can be viewed when it's executed on the scheduler.
=> File viewer hierarchical navigation and refresh

services/auth-server/app/app/__init__.py, services/auth-server/app/app/models.py, services/auth-server/app/config.py, services/auth-server/requirements.txt, services/orchest-api/app/app/__init__.py, services/orchest-api/app/app/apis/namespace_experiments.py, services/orchest-api/app/app/apis/namespace_pipelines.py, services/orchest-api/app/app/apis/namespace_projects.py, services/orchest-api/app/app/apis/namespace_runs.py, services/orchest-api/app/app/celery_app.py, services/orchest-api/app/app/core/tasks.py, services/orchest-api/app/app/models.py, services/orchest-api/app/app/utils.py, services/orchest-api/app/config.py, services/orchest-api/requirements-dev.txt, services/orchest-api/requirements.txt, services/orchest-ctl/app/cmdline.py, services/orchest-ctl/app/config.py, services/orchest-webserver/app/app/__init__.py, services/orchest-webserver/app/app/config.py, services/orchest-webserver/app/app/models.py, services/orchest-webserver/app/scripts/file_permission_watcher.py, services/orchest-webserver/requirements.txt, userdir/.orchest/database/.gitignore
This PR changes the database backend of Orchest from `sqllite` to `postgres`. A new service, `orchest-database`, is launched on start.
The PR affects `orchest-ctl` and services that were persisting their data: the `auth-server`, `orchest-webserver`, `orchest-api`, `celery-worker`.
=> Move Orchest database backend to postgres

services/orchest-ctl/app/cmdline.py, services/orchest-ctl/app/utils.py
This PR makes it so that user environments are invalidated when Orchest updates, to avoid issues related to mismatching versions of the `Orchest SDK` in different environments.
=> Invalidate user environment on update

orchest-sdk/python/orchest/transfer.py
This PR improves the error messages produced by the Orchest SDK when some input data cannot be found on disk and in the memory server. The resulting error message produced when an input cannot be found will contain the name of the pipeline step which supposedly produced the input.
=> Improve Orchest SDK error messages.

.flake8, services/orchest-api/app/app/apis/namespace_environment_builds.py, services/orchest-api/app/app/apis/namespace_environment_images.py, services/orchest-api/app/app/apis/namespace_experiments.py, services/orchest-api/app/app/apis/namespace_runs.py, services/orchest-api/app/app/core/environment_builds.py, services/orchest-api/app/app/core/pipelines.py, services/orchest-api/app/app/core/tasks.py, services/orchest-api/app/app/models.py, services/orchest-api/app/app/schema.py, services/orchest-api/app/app/utils.py, services/orchest-webserver/app/static/js/views/PipelineView.js
This PR makes it so that the status of an entity, such as a pipeline run or pipeline step, cannot be updated anymore once it has reached the state of ABORTED, FAILURE, or SUCCESS. This is to solve consistency and/or race conditions issues given by the fact that both the `orchest-api` and a celery task might be trying to PUT the status of an entity.
=> Improve orchest api status updates race conditions

services/orchest-webserver/app/static/js/views/PipelineView.js
Fixes #95 
This PR adds support for both <kbd>backspace</kbd> and <kbd>delete</kbd> for deleting both pipeline steps  and connections between the steps.
=> Support `backspace` and `delete` to delete components

orchest-sdk/python/orchest/parameters.py, services/orchest-api/app/app/core/tasks.py, services/orchest-webserver/app/app/core/pipelines.py, services/orchest-webserver/app/app/views/views.py
Since the pipeline definition is stored in JSON and JSON is unordered, every change to the pipeline definition could end up in large diffs. Instead of relying on the implicit order of keys in dictionaries, especially since the pipeline definition is also interacted with in Javascript, explicitly sort the keys.
Caveat: The order given by the user of the defined parameters is now also automatically sorted.
=> Minimally change pipeline definition for diffs

services/orchest-webserver/app/app/config.py, services/orchest-webserver/app/app/core/projects.py, services/orchest-webserver/app/app/views/views.py
This PR made the following changes:
- About #116 , This bug is caused by not catching the FileNotFoundError error, see line 147 of the script services/orchest-webserver/app/app/core/projects.py. `  shutil.rmtree(full_project_path)`
- Set `projects_dir` as a configuration property, such as: `app.config["USER_DIR"]`, because this variable is frequently combined in the code
=> Fix project detection failed: #116

services/memory-server/app/config.py, services/memory-server/app/main.py, services/memory-server/app/utils.py, services/orchest-api/app/app/apis/namespace_sessions.py, services/orchest-api/app/app/core/sessions.py, services/orchest-api/app/app/core/tasks.py, services/orchest-api/app/app/schema.py, services/orchest-api/app/app/utils.py, services/orchest-webserver/app/app/views/orchest_api.py, services/orchest-webserver/app/static/js/views/PipelineSettingsView.js
Due to Docker not supporting passing environment variables when starting a container (https://github.com/moby/moby/issues/7561), the `memory-server` now reads the `pipeline-definition` to determine the memory size for the internal Plasma store. As a side-effect only the `memory-server` has to be restarted for changes in the _Data passing memory size_ pipeline setting to take effect.
As an additional note, when starting the `memory-server` the `shm-size` is set to a large value to solely let the `memory-server` determine how much memory to consume (based on the setting). Mounting `/dev/shm` directly to the container's `/dev/shm` is not out of the box supported on Mac (and neither are [tmpfs mounts](https://docs.docker.com/storage/tmpfs/)).
Resolves #127
=> Memory size changes to take effect on memory-server restart

services/auth-server/app/app/views.py, services/orchest-webserver/app/static/css/main.scss, services/orchest-webserver/app/static/js/src/views/ProjectsView.js
This PR adds the possibility to add an `import_url` query argument to the `/projects` page. It will make it easier to directly import a project from a `git` supported URL.
It comes with a warning to make sure the user knows what they're doing:
In addition, this PR adds the ability to have login a redirect to a specific page by using the `redirect_url` query argument.
=> Add import url support, and post-login redirect.

services/orchest-ctl/app/cli/main.py, services/orchest-ctl/app/debug.py, services/orchest-ctl/app/orchest.py, services/orchest-ctl/tests/test_orchestapp.py
This PR adds an exit code to the `orchest-ctl` CLI `status` command. So that it can more easily be interacted with in an automated manner.
=> Add exit codes to CLI status

.flake8, orchest-sdk/python/orchest/__init__.py, orchest-sdk/python/orchest/parameters.py, orchest-sdk/python/orchest/pipeline.py
This PR expands the Orchest SDK to add single parameter `get` and `update` operations for both step and pipeline parameters.
It's still possible to `get` or `update` parameters in a batched manner by using the `get_params` and `update_params` functions.
Signatures:
`def get_step_param(key: str) -> Any:`
`def get_pipeline_param(key: str) -> Any:`
`def update_step_param(key: str, value: Any) -> None:`
`def update_pipeline_param(key: str, value: Any) -> None:`
=> Add single param get/update for step, pipeline

services/orchest-ctl/app/cli/main.py, services/orchest-ctl/app/cli/start.py, services/orchest-ctl/app/orchest.py, services/orchest-ctl/app/spec.py, services/orchest-webserver/app/app/config.py, services/orchest-webserver/app/app/views/views.py, services/update-server/app/app/config.py, services/update-server/app/app/views.py
Fixes the fact that the port which Orchest was started with was not preserved between restarts and updates.
=> Fix preserve port on restart

services/orchest-ctl/app/orchest.py, services/orchest-ctl/tests/test_orchestapp.py
A small PR to require `rabbitmq` to be ready before moving on with starting other services during the start of Orchest.
=> Rabbitmq to be ready before continuing with start

services/orchest-webserver/app/app/analytics.py, services/orchest-webserver/app/app/views/orchest_api.py
This PR expands the anonymized tracking of the Orchest API. Changes to already existing events:
- `pipeline run` --> `pipeline_run start`
- creating (POSTING) a job will not incorrectly send a `pipeline run` event anymore, but will instead send a `job create` event. The `job update` event will allow to infer the type of job (immediate, scheduled,  cron job).
=> Expand Orchest API tracking

docs/source/conf.py, orchest-sdk/python/requirements-dev.txt, orchest-sdk/python/requirements.txt, orchest-sdk/python/setup.py, scripts/run_tests.sh, services/memory-server/requirements-dev.txt, services/memory-server/requirements.txt
This PR upgrades the Orchest SDK and memory server service to `pyarrow` 4.0.0. The Orchest SDK requirements have intentionally been set with `pyarrow>=1.0.0,<=4.0.0` since testing has shown that the SDK would not break if a user was to install `pyarrow` release 1/2/3 when building an environment.
Some unused packages have also been removed from the SDK.
=> Upgrade Orchest SDK and memory server to pyarrow 4.0.0

services/orchest-api/app/app/apis/namespace_sessions.py, services/orchest-api/app/tests/namespaces/test_namespace_sessions.py
This PR makes it so that an ongoing interactive run will be aborted if the session is shut down or the memory server is restarted through the API, note that, as it stands, the GUI will not allow a user to restart the memory server if an interactive run is ongoing, but the session stop and memory server restart behaviours have been made consistent.
Fixes: #226
=> Fix abort run on session shutdown

docs/source/user_guide/sdk/python.rst
A single grain of contribution to an exiting project I discovered just today! 🤩  
Important to keep examples up to date and copy/paste ready for newcomers~
It looks like `orchest.get_params()` is now `orchest.parameters.get_params()`
=> [documentation update] fix get_params example

services/orchest-ctl/app/orchest.py, services/orchest-ctl/app/utils.py
=> Improv remove orchest dangling images on update and start

services/orchest-ctl/app/orchest.py, services/orchest-ctl/tests/test_orchestapp.py
This PR makes it so that `./orchest update` will lead to a full stop of Orchest if Orchest is running when not called with `--mode=web`.
=> Stop Orchest on CLI update

services/orchest-ctl/app/orchest.py
Fixes a bug in `orchest stop` related to unpacking a list that became empty after filtering.
=> Fix empty list unpacking

lib/python/orchest-internals/_orchest/internals/config.py, services/jupyter-server/start.sh, services/orchest-api/app/app/apis/namespace_sessions.py, services/orchest-api/requirements-dev.txt, services/orchest-api/requirements.txt, services/orchest-ctl/requirements-dev.txt, services/orchest-ctl/setup.py, services/orchest-webserver/app/app/__init__.py, services/orchest-webserver/requirements.txt, services/update-server/requirements.txt
On JupyterLab upgrade its old build files will be removed, whilst trying to maintain the user configurations.
I tested by swapping between commit `853809f2752c31f58528cc3a860bab9d5ca59003` (a commit before the JupyterLab upgrade) and rebuilding Orchest each time (which is quick due to Docker's caching system).
My flow:
* `sudo rm -rf lab && git checkout lab && ll lab` in `userdir/.orchest/user-configurations/jupyterlab`
* `git checkout 853809f2752c31f58528cc3a860bab9d5ca59003`
* `scripts/build_container.sh`
* Rebuilding the user configured JupyterLab (in which I put `pip show jupyterlab` to inspect that it is running on an older/newer version).
* This now populates the `lab` directory.
* Stop Orchest and rebuild master (after a `git checkout master`)
* Rebuild user configured JupyterLab
* …
=> Fix user configuration migration on JupyterLab upgrade

lib/design-system/package/CHANGELOG.md, lib/design-system/package/package.json, lib/design-system/package/src/components/alert.tsx
Adds the "backwards" direction to the previous button (which was missed off in the implementation)
=> Fix Alert pagination

services/orchest-webserver/client/src/styles/main.scss, services/orchest-webserver/client/src/views/EnvironmentEditView.jsx
- Slightly increases spacing between form fields (I tried making it larger but it was just too much)
- Uses Stitches-driven vars to help migrate styles slowly over to Stitches (and at least align our use-case styles in the meantime)
It's important to know that this is really just something to improve short-term, long-term as we migrate to Stitches we can look into improving our overall forms design and structure
|Before|After|
|--|--|
| <img width="1259" alt="Screenshot 2021-05-21 at 14 05 35" src="https://user-images.githubusercontent.com/7349341/119127970-b527fc00-ba3d-11eb-938c-a62c43c97ac1.png"> | <img width="1259" alt="Screenshot 2021-05-21 at 14 03 05" src="https://user-images.githubusercontent.com/7349341/119127961-b22d0b80-ba3d-11eb-903c-076188e56d01.png"> | 
| Diff |
| --|
| …
=> Fix: "Text is hard to read in the 'environments' tab"

services/orchest-webserver/client/src/views/PipelineView.jsx
When in "read only" mode, double-clicking on a pipeline step will now trigger the "view file" action rather than erroneously trying to open Jupyter.
=> Fix "Double Click" Behaviour

services/base-images/runnable-shared/runner/run.py, services/base-images/runnable-shared/runner/runner/runners.py, services/orchest-api/app/app/core/pipelines.py
This changes the behavior of the default working directory to be more consistent throughout Orchest.
The change is: originally the working directory would always be the pipeline file directory. Now it's the directory in which the file lives that's being executed.
=> Change working directory to be relative to the file being executed

services/jupyter-server/requirements.txt, services/jupyter-server/start.sh
For the time being we're reverting back to JupyterLab 3.0.X as the 3.1 version has too many stability issues at the moment.
=> Revert JupyterLab 3.1 due to stability issues.

services/auth-server/client/tsconfig.json, services/orchest-webserver/client/tsconfig.json
As of now, our `lint` step hasn't actually been catching type errors via `// @ts-check` 🥴
=> Include JS files in type checks

lib/javascript/mdc/package.json, lib/javascript/utils/package.json
Adds `esbuild --watch` flags to `lib` packages to enable hot-reloading
(in the same manner that [`design-system` watches](https://github.com/orchest/orchest/blob/master/lib/design-system/package/package.json#L21) for changes)
=> Add watch scripts to lib packages

services/orchest-webserver/client/src/views/EnvironmentEditView.jsx
Fixes: #279 
By default JupyterLab and the Enterprise Gateway allow all kernel names. The problem was that double quotation marks `"` need to be escaped, e.g. `\"`. Otherwise the `kernel.json` would be invalid as the value could look like `"value"more"`, which is invalid JSON.
=> Fixes #279

services/jupyter-enterprise-gateway/kernel-override/kernel.json
Closes: #204 
As stated in the issue, the default kernel seems to be baked into certain Jupyter parts. Without digging into this I realized there is another solution: overwriting the `kernel.json` with invalid JSON. This will throw the following error (in the EG) every time the kernels are loaded:
```text
[W 2021-06-03 12:25:22.558 EnterpriseGatewayApp] Error loading kernelspec 'python3'
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 257, in get_all_specs
spec = self._get_kernel_spec_by_name(kname, resource_dir)
File "/opt/conda/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 200, in _get_kernel_spec_by_name
return self.kernel_spec_class.from_resource_dir(resource_dir)
File …
```
=> Produce JSONDecodeError to remove default kernel

services/orchest-api/app/app/core/tasks.py, services/orchest-webserver/app/app/utils.py, services/orchest-webserver/app/app/views/views.py, services/orchest-webserver/client/src/components/JobList.jsx, services/orchest-webserver/client/src/styles/main.scss
Closes: #247
The warning is added to the modal when creating a job (but only visible if the snapshot size would exceed the 50MB threshold):
Note: This is the same style of warning when creating an invalid cron string.
=> Add warning when snapshot size exceeds 50MB

services/orchest-webserver/client/src/views/PipelineView.jsx
Fix selection behavior in pipeline editor.
More precisely, connections should behave similar to steps:
* Whenever selected, deselect other connections and steps.
* Whenever something else is selected, deselect itself.
* Selecting a connection would not deselect an already select step.
* Selecting a step would not deselect a selected connection.
For example (without using the Ctrl + click feature):
=> Fix selection behavior in pipeline editor

docs/source/user_guide/environments.rst, services/orchest-api/app/app/core/docker_utils.py, services/orchest-api/app/app/core/environment_builds.py
This PR makes it so that building an environment with a custom base image uses `sudo` only if necessary, moreover, a help message is injected into the log stream if `find` is not installed in the base image, or if the base image does not have USER root while also not having `sudo` installed.
=> Do not use sudo if it's not necessary

services/orchest-webserver/app/app/core/projects.py, services/orchest-webserver/app/app/utils.py
This PR alters the way the `orchest-webserver` is doing most of its file system operations by replacing calls to `shutil` with `subprocess`. The reason is that `shutil`  (and os.system) is not monkey patched by eventlet while subprocess is. This makes it so that the webserver won't be blocked while, for example, taking a snapshot of a project for a job.
Fixes #304
=> Use subprocess for non blocking FS copy and removal in webserver

services/orchest-api/app/app/core/sessions.py, services/orchest-api/app/app/utils.py
Fixes an issue where code shared by the `orchest-api` and `celery-worker` would fail because it contained a resource that was not available to the `celery-worker`, the app logger.
=> Use a different logger when running as celery

docs/source/user_guide/services.rst, services/orchest-api/app/app/core/sessions.py, services/orchest-api/app/app/schema.py
Service inherited environment variables take priority over "in place" defined ones.
=> Inherited env vars have priority over service defined ones

services/orchest-ctl/app/scripts/git-update.sh
Fixes the `git-update.sh` script by not using `--show-current` as it is a new feature of git, which is not run in the `orchest-ctl` that executes the `git` command. (For reference the `orchest-ctl` runs `git version 2.20.1` whilst for `--show-current` version `2.22.0` is required.)
=> Fix orchest update mechanism

lib/design-system/package/CHANGELOG.md, lib/design-system/package/package.json
As `files` key isn't supported by `pnpm`, we'll need to omit it instead (as files weren't being published)
=> Patch Latest Design System Release

services/orchest-webserver/client/src/App.tsx, services/orchest-webserver/client/src/hooks/orchest/provider.jsx, services/orchest-webserver/client/src/types.d.ts, services/orchest-webserver/client/src/utils/webserver-utils.js, services/orchest-webserver/client/src/views/ConfigureJupyterLabView.jsx, services/orchest-webserver/client/src/views/EditJobView.jsx, services/orchest-webserver/client/src/views/EnvironmentEditView.jsx, services/orchest-webserver/client/src/views/PipelineSettingsView.jsx, services/orchest-webserver/client/src/views/ProjectSettingsView.jsx, services/orchest-webserver/client/src/views/SettingsView.jsx
As a side effect of #317, `setUnsavedChanges`'s logic was behaving incorrectly – firing again after first dismissal 
I started off by trying to debug this in the existing setup (with `window.orchest`) but it became incredibly tricky to find the root cause. 
Instead, I used this opportunity to remove further logic from `App.tsx`, moving all `setUnsavedChanges` functionality to the global context. Where needed, local `unsavedChanges` state has been updated to keep global state in sync.
=> Move unsavedChanges/setUnsavedChanges to useOrchest

orchest, services/orchest-api/app/config.py, services/orchest-ctl/app/cli/main.py, services/orchest-ctl/app/config.py, services/orchest-ctl/app/orchest.py, services/orchest-ctl/app/utils.py
Adds functionality to the CLI to run a pipeline as a one-time job.
To try it out:
```bash
./orchest run --job=test --project=quickstart --pipeline="california-housing"
```
* Q: Do we want it as a hidden or public CLI command? I would opt for public since we already indicate we are in alpha.
* A: Ended up with public.
* Q: The CLI now reads the pipeline definition (which it needs to create the strategy json for the job) from the `userdir`. Is this against our design decisions? And if so, do we want to add a dedicated endpoint webserver?
* A: Used already existing webserver endpoint.
* Q: How do we want to handle environment variables? I now opted to let the users use project and pipeline environment variables, because passing variables through the CLI, e.g. `--name=value`, would cause them …
=> Run a pipeline through the CLI

services/orchest-webserver/client/src/App.tsx
Prevents the default view from being loaded twice on mount (`loadDefaultView` is handled by `initializeFirstView`)
Closes #333
=> Prevent loadDefaultView firing twice

services/orchest-webserver/client/src/App.tsx
Adds the context `project_uuid` to route `_generateView` dependencies.
Fixes: #334
=> Fix project selector routing behaviour

services/orchest-ctl/app/debug.py
Fixes the name of a log file that the debug dump expected to be there in the celery container.
=> Fix debug expected celery log file name

services/orchest-webserver/app/scripts/background_tasks.py, services/orchest-webserver/client/src/views/ProjectsView.jsx
Select imported project automatically
Closes: https://github.com/orchest/orchest/issues/343
This also fixes "resetting" of the selected project to the first project in Orchest when visiting the /projects page.
=> Select imported project automatically

services/orchest-webserver/client/src/components/Dialogs.jsx
Remove dialog on buildComplete
=> Remove dialog on buildComplete

services/orchest-ctl/app/cli/main.py, services/orchest-ctl/app/orchest.py
Add `--wait` to `orchest run ...` to wait for the pipeline run to finish executing. This makes the CLI command blocking. Default is `--no-wait`, i.e. not waiting/blocking.
=> Improvement: add `--wait` to CLI `run` command

services/orchest-webserver/client/src/components/Layout/OnboardingDialog/OnboardingDialogCarousel/use-onboarding-dialog-carousel.js, services/orchest-webserver/client/src/components/Layout/OnboardingDialog/use-onboarding-dialog.js
This is a temporary work-around to avoid issuing requests for the onboarding component.
@joe-bell I think we're using SWR in the wrong way here. It looks to me like you're using it for hook-style state management. This was triggering requests to a random endpoint (that doesn't exist). Let's sync on this next week.
=> Replace fetcher with no-op promise to avoid requests.

services/orchest-ctl/app/cli/main.py, services/orchest-ctl/app/orchest.py, services/orchest-webserver/client/src/components/Layout/OnboardingDialog/OnboardingDialogCarousel/use-onboarding-dialog-carousel.js, services/orchest-webserver/client/src/components/Layout/OnboardingDialog/use-onboarding-dialog.js
* Adds `--wait` option to the `run` CLI command to block until the pipeline has finished executing.
* Avoids making unnecessary request regarding the new onboarding dialog.
=> v2021.06.5

README.md, docs/source/getting_started/installation.rst, services/nginx-proxy/orchest.conf
Disable IPv6 in nginx. We weren't attching to the IPv6 address in the Docker network forwarding anyway. And disabling the listen is required to fix https://github.com/docker/for-linux/issues/914.
This partially solves https://github.com/orchest/orchest/issues/9. It still requires manual disabling of IPv6 in Linux.
=> Disable IPv6 in nginx-proxy

services/orchest-webserver/client/src/components/Layout/OnboardingDialog/OnboardingDialogCarousel/use-onboarding-dialog-carousel.js, services/orchest-webserver/client/src/components/Layout/OnboardingDialog/use-onboarding-dialog.js
**Why SWR?**
To avoid wrapping our `App.tsx` with endless `Context.Provider`s for all our different hooks, SWR was chosen for shared state – following [this article written by **the library's co-maintainer**](https://paco.sh/blog/shared-hook-state-with-swr).
The article outlines well the headaches that come with maintaining shared state, with a solution that leverages client-side cache – thoughts that echo my own.
**Workaround**
After merging, @yannickperrenet/@ricklamers noticed that SWR was trying to "fetch" the key as an endpoint. As a workaround, this fetcher was set to a `null`-returning promise.
This PR switches that `null`-returning Promise workaround to `null` – skipping the [optional `fetcher`](https://swr.vercel.app/docs/options) option altogether. It seems like this is a …
=> Switch SWR fetcher to null

services/orchest-webserver/client/src/components/EnvironmentList.jsx
=> Show an 'NOT BUILT' status instead of an empty span

services/auth-server/app/app/views.py, services/auth-server/client/src/App.tsx, services/auth-server/client/src/main.tsx, services/auth-server/client/src/views/Login.tsx
The view to load (either `login` or `admin`) in the `auth-server` was determined by 
```javascript
let view = window.location.href.split("/").slice(-1)[0];
```
which incorrectly handles URLs such as `http://localhost:8000/login?redirect_url=/environments` (`view` would be `environments`).
This PR fixes the issue, making the following possible again:
* http://localhost:8000/login?redirect_url=/environments
*  http://localhost:8000/login?redirect_url=/projects&import_url=https://github.com/orchest/quickstart
> FYI the issue was (unknowingly) reintroduced in a6770357512250425ac927aa1cae6227ed760f1f.
=> Fix query args passing at `/login`

cypress/integration/onboarding.spec.ts, services/orchest-webserver/client/src/views/HelpView.tsx
1. Cleans up existing onboarding spec to make use of `before` and other hooks more efficiently – which encourages grouping in a more logical manner
2. Extend onboarding spec to check toggling in `/help`
=> Extend and cleanup Onboarding Spec

services/orchest-webserver/client/src/types.d.ts, services/orchest-webserver/client/src/utils/webserver-utils.ts, services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx, services/orchest-webserver/client/src/views/EditJobView.tsx, services/orchest-webserver/client/src/views/EnvironmentEditView.tsx, services/orchest-webserver/client/src/views/EnvironmentsView.tsx, services/orchest-webserver/client/src/views/FileManagerView.tsx, services/orchest-webserver/client/src/views/FilePreviewView.tsx, services/orchest-webserver/client/src/views/HelpView.tsx, services/orchest-webserver/client/src/views/JobView.tsx, services/orchest-webserver/client/src/views/JobsView.tsx, services/orchest-webserver/client/src/views/JupyterLabView.tsx, services/orchest-webserver/client/src/views/LogsView.tsx, services/orchest-webserver/client/src/views/ManageUsersView.tsx, services/orchest-webserver/client/src/views/PipelineSettingsView.tsx, services/orchest-webserver/client/src/views/PipelinesView.tsx, services/orchest-webserver/client/src/views/ProjectSettingsView.tsx, services/orchest-webserver/client/src/views/ProjectsView.tsx, services/orchest-webserver/client/src/views/SettingsView.tsx, services/orchest-webserver/client/src/views/UpdateView.tsx
Adds `TViewProps` type and the `TViewPropsWithRequiredQueryArgs` helper type to ensure our views are better typed
=> Introduce TViewProps Types

lib/python/orchest-internals/_orchest/internals/utils.py, services/orchest-api/app/app/apis/namespace_jobs.py, services/orchest-api/app/app/apis/namespace_pipelines.py, services/orchest-api/app/app/apis/namespace_projects.py, services/orchest-api/app/tests/namespaces/test_namespace_jobs.py, services/orchest-api/app/tests/namespaces/test_namespace_pipelines.py, services/orchest-api/app/tests/namespaces/test_namespace_projects.py, services/orchest-api/app/tests/namespaces/test_namespace_runs.py, services/orchest-webserver/app/app/compat.py, services/orchest-webserver/app/app/views/views.py, services/orchest-webserver/client/src/components/EnvVarList.tsx, services/orchest-webserver/client/src/styles/main.scss, services/orchest-webserver/client/src/utils/webserver-utils.ts, services/orchest-webserver/client/src/views/EditJobView.tsx, services/orchest-webserver/client/src/views/PipelineSettingsView.tsx, services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
Adds validation to environment variable names.
Fixes: #376 
@joe-bell, when it comes to the front end, the following things needs to be validated:
- project env variables
- pipeline env variables
- jobs env variables
- services env variables and inherited env variables
Only the name of environment variables needs to be validated. The backend considers `^[0-9a-zA-Z\-_]+$` as valid, the BE and the FE are to be in sync with this.
=> Environment variables name validation

docs/source/user_guide/other.rst, lib/python/orchest-internals/_orchest/internals/utils.py, services/orchest-api/celery_daemon_configs/worker_jobs.conf, services/orchest-ctl/app/debug.py, services/orchest-ctl/app/spec.py, services/orchest-ctl/app/utils.py, services/orchest-webserver/app/app/__init__.py, services/orchest-webserver/app/app/utils.py, services/orchest-webserver/app/app/views/views.py, services/orchest-webserver/client/src/views/SettingsView.tsx
Allows the user to control the level of parallelism of job runs through the settings. Once the settings are saved Orchest must be restarted for the change to take effect.
=> Allow the user to control the level of job runs parallelism

README.md, docs/source/getting_started/installation.rst, services/orchest-ctl/app/config.py, services/orchest-ctl/app/orchest.py, services/orchest-ctl/tests/test_orchestapp.py
The improved messages should help the users debug issues when installing or updating Orchest. For example, when the user is running out of disk space and therefore the installation of Orchest does not complete successfully, we now prompt the user.
Secondly, the old proposed `orchest --help` does very little to verify the installation. Now we propose using `orchest version --ext` to do so, because it checks whether:
* all Orchest owned images are pulled
* all images run the same version of Orchest
Also a partial solution for #392.
=> Improve messages for `orchest install`, `update` and `version`

docs/source/_static/css/custom_styles.css, docs/source/_templates/layout.html, docs/source/_templates/searchbox.html, docs/source/conf.py
**NOTE:** does not work yet!
Powers the documentations search by algolia.
We use the `press` theme for our docs ([reference](https://github.com/schettino72/sphinx_press_theme)), however in their `layout.html` they have
```html
<script src="{{ pathto('_static/theme.js', 1)}}" defer></script>
```
which prohibits the search from working. If you comment this line out, then the search works.
To, locally, comment this line out you can:
1. `python -m site` to find your site packages
2. open `sphinx_press_theme/layout.html`
> which prohibits the search from working
Why and how exactly, I do not know...
=> Integrate algolia search into docs

docs/source/user_guide/sdk/R.rst, docs/source/user_guide/sdk/index.rst
Updates the `Orchest SDK` section of the docs with a section related to the `R` language, which explains how to interface with the Orchest SDK through `reticulate`.
=> Add R Orchest SDK docs

services/orchest-api/app/app/apis/namespace_jobs.py, services/orchest-api/app/app/models.py, services/orchest-api/app/app/schema.py, services/orchest-api/app/app/utils.py, services/orchest-webserver/app/app/analytics.py, services/orchest-webserver/app/app/views/orchest_api.py, services/orchest-webserver/client/src/components/Status.tsx, services/orchest-webserver/client/src/views/JobView.tsx
This PR introduces cron jobs pausing. A running cronjob can be paused, and a paused cronjob can be resumed. Runs of a cronjob that have already been scheduled (PENDING, STARTED) will continue running when the cron job is paused.
=> Cron job pausing

.github/workflows/python-tests.yml, README.md, scripts/run_tests.sh, services/orchest-api/app/app/apis/namespace_jobs.py, services/orchest-webserver/app/app/__init__.py, services/orchest-webserver/app/app/analytics.py, services/orchest-webserver/app/app/config.py, services/orchest-webserver/app/app/core/jobs.py, services/orchest-webserver/app/app/error.py, services/orchest-webserver/app/app/views/orchest_api.py, services/orchest-webserver/app/tests/conftest.py, services/orchest-webserver/app/tests/test_jobs.py, services/orchest-webserver/app/tests/test_utils.py, services/orchest-webserver/client/src/styles/main.scss, services/orchest-webserver/client/src/views/EditJobView.tsx, services/orchest-webserver/client/src/views/JobView.tsx
This PR introduces job duplication, which allows duplicating a job, creating a job with the latest code and environments but inheriting the settings of the job that is being duplicated.
The environment variables of the new job are resolved by merging the current project and pipelines environment variables, then adding the inherited job environment variables. Note that this implies that environment variables that were "inherited" by the job that is being duplicated from project/env variables cannot be distinguished from environment variables that were defined in the job. This might be of interest given that if those project/pipeline variables do not exist anymore it might make more sense to not include them in the newly defined job.
Job parameters are resolved by:
- removing parameters …
=> Job Duplication

cypress/support/commands.ts, cypress/support/index.ts, services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx
When I run Cypress on Mac with scripts like `pnpm run cy:open`, the tests hang and then throw timeout because it couldn't find the test id. According to the [official doc](https://github.com/testing-library/cypress-testing-library#config-testidattribute),  the configuration can be done on level up in `cypress/support/index.ts` instead of inside of the test context. This solves my issue on Mac.
```
import { configure } from "@testing-library/cypress";
configure({ testIdAttribute: "data-test-id" });
```
=> Fix integration tests hanging on Mac

services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useHotKey.ts
In the Pipeline Editor view, using Ctrl + Enter hotky always ends up a "no active session" error.
=> Ctrl + Enter always ends up "No Session" error

lib/javascript/mdc/src/MDCLinearProgressReact.tsx, services/orchest-webserver/app/app/views/views.py, services/orchest-webserver/client/src/styles/main.scss, services/orchest-webserver/client/src/views/SettingsView.tsx
This PR adds an entry to the settings view that shows the disk usage of the disk that docker is making use of.
=> disk information in settings

lib/javascript/mdc/src/MDCDialogReact.tsx, services/orchest-webserver/client/src/projects-view/ImportDialog.tsx
this is to prevent user losing import progress. The downside is that if user was just checking the functionality, user cannot easily close it with ESCAPE key or mouse click outside.
=> Disable close for import dialog

services/orchest-webserver/client/src/projects-view/ImportDialog.tsx
When importing an example or project, the CLOSE button should be hidden to freeze the dialog until success or failure.
=> hide close button when importing

docs/source/user_guide/sdk/R.rst
Otherwise throws an error like: `Error in py_get_attr_impl(x, name, silent): AttributeError: module 'orchest' has no attribute 'output_to_disk'`
=> Specify submodule when using orchest functions

docs/source/developer_guide/implementation_details.rst, services/auth-server/app/app/utils.py, services/auth-server/app/app/views.py, services/auth-server/app/config.py, services/auth-server/requirements.txt, services/nginx-proxy/Dockerfile, services/nginx-proxy/orchest.conf, services/nginx-proxy/service.conf, services/orchest-api/app/app/apis/__init__.py, services/orchest-api/app/app/apis/namespace_services.py, services/orchest-api/app/app/schema.py, services/orchest-webserver/client/src/Routes.tsx, services/orchest-webserver/client/src/components/ProjectSelector.tsx, services/orchest-webserver/client/src/components/ServiceForm.tsx, services/orchest-webserver/client/src/hooks/orchest/provider.tsx, services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx, services/orchest-webserver/client/src/projects-view/ProjectsView.tsx, services/orchest-webserver/client/src/styles/main.scss, services/orchest-webserver/client/src/types.d.ts
Enable services that have no authentication. This can be useful for OAuth flows or hosting Streamlit dashboard.
Fixes: https://github.com/orchest/orchest/issues/487
=> Enable authless services

services/jupyter-server/requirements.txt, services/orchest-webserver/client/src/hooks/orchest/provider.tsx, services/orchest-webserver/client/src/jupyter/Jupyter.tsx, services/orchest-webserver/client/src/views/JupyterLabView.tsx
Show loading screen until iframe load completes.
=> Show loading screen until iframe load completes.

docs/source/user_guide/other.rst, lib/python/orchest-internals/_orchest/internals/errors.py, lib/python/orchest-internals/_orchest/internals/utils.py, services/auth-server/app/add_user.py, services/auth-server/app/app/utils.py, services/auth-server/app/app/views.py, services/auth-server/app/main.py, services/orchest-api/celery_daemon_configs/worker_interactive.conf, services/orchest-ctl/app/debug.py, services/orchest-ctl/app/spec.py, services/orchest-ctl/app/utils.py, services/orchest-webserver/app/app/__init__.py, services/orchest-webserver/app/app/utils.py, services/orchest-webserver/app/app/views/views.py, services/orchest-webserver/app/tests/conftest.py, services/orchest-webserver/app/tests/tmp-artifacts/.gitignore, services/orchest-webserver/client/src/views/SettingsView.tsx
Fixes: #501 
This PR also introduces the `GlobalOrchestConfig` class and refactors all access to the global Orchest config file (`~/.config/orchest/config.json` on the host) to use the class. The class ensures all configuration options have a default value and are validated when changed, and certain preset options in the file cannot be changed when running with `--cloud`.
@fruttasecca Can you back up your current config file and then build the branch and try to use Orchest? That would be great, thank you!
=> Increased run parallelism for jobs and interactive runs

services/orchest-ctl/app/utils.py
This is a rather small fix to improve the speed of `find` in our particular case. Essentially, we are filtering out directories for which the `g+s` flag is already set before setting it.
This has been tested on a cloud instance that was affected by this issue, and the difference is substantial, i.e. 10 minutes vs 6 seconds. I have also tested it locally with around `1600000` directories living in the `/data` directory, and it took 14 seconds. Of course, this is because we are leveraging the fact that most or all directories already have the flag.
I also took some time to test [fd](https://github.com/sharkdp/fd), its batched execution is way faster while the non batched execution did not bring much difference when testing with a single thread. The batched execution can't currently be used …
=> Set g+s to directories not having g+s already set

services/base-images/base-kernel-julia/Dockerfile, services/base-images/base-kernel-julia/augment-root.sh, services/base-images/base-kernel-py-gpu/Dockerfile, services/base-images/base-kernel-py-gpu/augment-root.sh, services/base-images/base-kernel-py/Dockerfile, services/base-images/base-kernel-py/augment-root.sh, services/base-images/base-kernel-r/Dockerfile, services/base-images/base-kernel-r/augment-root.sh, services/base-images/runnable-shared/bootscript.sh, services/base-images/runnable-shared/runner/pyrightconfig.json, services/base-images/runnable-shared/runner/requirements-user.txt, services/base-images/runnable-shared/runner/requirements.txt, services/base-images/runnable-shared/runner/run.py, services/base-images/runnable-shared/runner/runner/preprocessors.py
Fixes: #425 
You can try it out by importing: https://github.com/yannickperrenet/orchest-notebook-runner-pr
=> Use separate Python environment to do pipeline runs

lib/python/orchest-internals/_orchest/internals/config.py, services/orchest-api/app/app/core/docker_utils.py, services/orchest-api/app/app/core/pipelines.py, services/orchest-api/app/app/core/sessions.py, services/orchest-webserver/app/app/res/kernels/launch_docker.py
This will make it so that, during periods of CPU contention, core Orchest services are given priority over containers that the user has launched through Orchest. This is a minor QOL improvement especially aimed at the cloud. The PR is a single commit and the content is intentionally simple given the not too far k8s migration that might condition or be conditioned by such changes.
s.
=> Orchest core containers cpu priority over user Orchest containers

lib/python/orchest-internals/_orchest/internals/utils.py
We need to fall back on default values as otherwise the application won't start for people who had valid values in Orchest release X, but invalid (due to a change on our side) values in release X+i (where i >= 1)
=> Fall back on default values for invalidated global config options 

services/orchest-webserver/client/src/projects-view/ProjectsView.tsx
Resolves: #555, #521 
I left the `validateProjectNameAndAlert` code in there as I figured it is defensive programming. However, with this change that code should never run so removing it is also not a bad idea.
What do you think? @iannbing
=> Substitute invalid characters on project name creation

lib/javascript/utils/src/typed.ts, services/orchest-webserver/app/app/analytics.py, services/orchest-webserver/app/app/views/orchest_api.py
Improves the telemetry of an environment build event by including the following information:
- language (str)
- gpu_support (boolean)
- uses_orchest_base_image (boolean)
=> Improve environment build telemetry

services/jupyter-server/Dockerfile
Enables JupyterLab widgets by default.
It is a feature many people use and configuring JupyterLab through our UI is something not that many people do, so instead of users having to add:
```bash
pip install jupyterlab-widgets
```
it is baked into the image.
=> Enable jupyterlab widgets by default

services/nginx-proxy/orchest.conf
The rule has probably been there from the early days and was never
removed once we had an api-proxy inside the webserver.
@nhaghighat This means that the [orchest-api ingress](https://github.com/orchest/orchest/blob/feat/k8s/deploy/helm/charts/orchest-api/templates/ingress.yaml) is no longer needed, right?
=> Remove unused `/api-proxy/` location from nginx conf

services/orchest-webserver/client/src/components/HeaderBar.tsx, services/orchest-webserver/client/src/contexts/SessionsContext.tsx, services/orchest-webserver/client/src/hooks/useSessionsPoller.ts, services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx, services/orchest-webserver/client/src/pipeline-view/LogsView.tsx, services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx, services/orchest-webserver/client/src/pipelines-view/PipelineList.tsx, services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx, services/orchest-webserver/client/src/views/JupyterLabView.tsx
Move useSessionsPoller into HeaderBar to easier session polling management.
=> Improv/move sessions poller to HeaderBar

.github/workflows/integration-tests.yml, scripts/clean_userdir.sh, services/orchest-ctl/app/cli/main.py, services/orchest-ctl/app/cli/start.py, services/orchest-ctl/app/orchest.py
It shouldn't be needed to fix permissions anyways and for large userdirs this `find` command can take very long.
=> Don't try to fix userdir permissions in `--cloud`

services/orchest-webserver/Dockerfile, services/orchest-webserver/app/app/config.py, services/orchest-webserver/app/app/core/projects.py, services/orchest-webserver/app/app/utils.py
Fixes: #599 
The changes can be summarized as:
* Swap out `cp -r` for an `rsync` command.
* Populate a root-level `.gitignore` file that can be passed to `rsync` to ignore the files when copying.
It makes sense that `cp` is generally more performant since it doesn't do any intelligent checking whether files have to be copied. However, now that we don't use `cp` we can skip copying large files (e.g. `logs` and `data` generated by the steps). In addition, a project directory is probably limited in size and its number of files.
The experimentation below showed promising results.
```bash
head -c 10GB /dev/zero > bigfile
time cp bigfile largefile
-> cp bigfile largefile  0,07s user 4,64s system 95% cpu 4,935 total
rm largefile
time rsync -aWHAX bigfile largefile
-> rsync -aWHAX bigfile …
```
=> Reduce snapshot size by ignoring patterns defined in the `.gitignore`

services/orchest-webserver/client/src/hooks/useCheckUpdate.tsx
Who doesn't want to know why they should update? So to inform the user, link to the latest release on our GitHub releases page: https://github.com/orchest/orchest/releases/latest
(Note: an update prompt would not actually be displayed if you have these versions. Just for testing purposes.)
=> Add a link to the release notes to the update prompt

services/auth-server/client/src/views/Login.tsx
Fix parsing the response so that users get prompted the reason why they could not login with the provided credentials
@ricklamers @iannbing Wouldn't it be better to always give the same reason? Because now an attacker could learn whether he/she provided an existing username.
=> Display message to users on invalid login credentials

services/orchest-webserver/client/src/pipeline-settings-view/useFetchPipelineMetadata.ts, services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx, services/orchest-webserver/client/src/pipeline-view/useStepExecutionState.ts
Fix unexpected behaviors in PipelineView read-only mode:
- run status polling was not started
- pipeline settings view was broken because env variables was still null in first several renders.
=> Fix read-only mode step status polling and pipeline settings

deploy/helm/charts/orchest-api/templates/deployment.yaml, deploy/helm/charts/orchest-api/templates/rbac.yaml, deploy/helm/templates/_cluster-role.tpl
Adds permissions to the `celery-worker` and `orchest-api` that are required for their tasks.
=> Add celery-worker and orchest-api cluster permissions

services/orchest-webserver/client/src/contexts/AppContext.tsx, services/orchest-webserver/client/src/hooks/useSendAnalyticEvent.ts
Currently Confirm dialog crashes if the content contains React elements.
=> Fix crashing when Confirm dialog has React elements

services/orchest-ctl/app/cli/main.py, services/orchest-ctl/app/orchest.py
In the edge case where Orchest is updated or restarted directly, the flag to skip the `find` command to fix userdir permissions was not passed. Now it is.
This resulted in the `find` command still running in certain cases, making the restart of Orchest (possibly) very slow.
Should've been caught in #669.
=> Do not run fix userdir permissions after restarting with `--cloud`

cypress/cypress/integration/auth.spec.ts, cypress/cypress/integration/environments.spec.ts, cypress/cypress/integration/file-system-interactions.spec.ts, cypress/cypress/integration/interactive-runs.spec.ts, cypress/cypress/integration/jobs.spec.ts, cypress/cypress/integration/onboarding.spec.ts, cypress/cypress/integration/pipelines.spec.ts, cypress/cypress/integration/projects.spec.ts, cypress/cypress/integration/services.spec.ts, cypress/cypress/support/commands.ts, services/orchest-webserver/client/src/components/CommandPalette.tsx, services/orchest-webserver/client/src/hooks/useCheckUpdate.tsx, services/orchest-webserver/client/src/hooks/useLocalStorage.ts
Cypress tests were failing because cy.intercept was not functioning.
=> Fix failing end-to-end tests for Orchest update checks

services/orchest-webserver/client/src/pipeline-view/PipelineDetails.tsx, services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx, services/orchest-webserver/client/src/views/FilePreviewView.tsx
When trying to navigate to subsequent views of pipeline editor (i.e. pipeline settings, logs, file preview), the view would break because run uuid was passed along (thus it was considered as a job run, instead of an interactive run).
=> Fix page loading when visiting file preview, pipeline settings, logs with an interactive run

services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx, services/orchest-webserver/client/src/pipeline-view/useStepExecutionState.ts
Currently a job run can only be canceled in pipeline run table. 
This PR adds the cancel run button in pipeline view, same as the interactive run.
~Plus a minor improvement, pipeline view will stop polling job run status if pipeline is not running.~
Fixes: #701
=> Allow cancel a job run in pipeline editor

services/orchest-webserver/client/src/components/CommandPalette.tsx
This PR fixes the following bugs in Command Palette:
- broken if there are entities with same name in the same project
- unable to click to execute command
=> Fix command palette broken when entities with same name

services/base-images/runnable-shared/runner/run.py
This adds more functionality to the scripts, without breaking any of the functionality as `bash` is a superset of `sh`.
In case you are looking to test it out. The following does work (without any errors) with the given change, but did not work before:
```bash
function sayIt {
echo "I AM SAYING IT"
}
sayIt
```
The `function` keyword is not recognized by `sh`, the `sh` equivalent would be:
```sh
sayIt() {
echo "I AM SAYING IT"
}
sayIt
```
=> Invoke scripts with the `sh` extension using `bash`

services/orchest-webserver/client/src/components/ServiceForm.tsx, services/orchest-webserver/client/src/hooks/useFetchPipelineJson.ts, services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx, services/orchest-webserver/client/src/utils/webserver-utils.ts
This PR fix the issue for service name collision and breakage.
If user attempts to rename a service with an existing name, the form will show a proper error message and disable all other fields until user gives a unique name.
Fixes: #375
=> Fix service name collision or breakage

services/orchest-api/app/app/apis/namespace_jobs.py
Moves `process_stale_environment_images` to the background scheduler.
`process_stale_environment_images` could potentially hang whilst waiting
for the Docker Engine (talking about I/O here) and by running it on the
background scheduler the request should return almost instantly instead
of potentially hang.
This fix was talked about in #693.
=> Make `/jobs` `DELETE` endpoints resolve quicker

services/orchest-webserver/client/src/components/DataTable.tsx, services/orchest-webserver/client/src/components/EnvironmentList.tsx, services/orchest-webserver/client/src/jobs-view/JobList.tsx, services/orchest-webserver/client/src/pipelines-view/PipelineList.tsx, services/orchest-webserver/client/src/projects-view/ProjectsView.tsx
Currently DataTable doesn't handle errors internally when deleting selected rows. This might cause "frozen" state if failed to delete selected rows within DataTable.
=> Improve error handling for deleting selected rows

services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
It was not possible to delete a service. Now it is possible again.
**Todo**
~~- [ ] Add a Cypress test for service deletion. Currently we also just do `rm -rf` to remove state so we never tested for the behavior.~~ --> https://github.com/orchest/orchest/issues/719
=> Fix services deletion

services/orchest-webserver/client/src/components/DataTable.tsx, services/orchest-webserver/client/src/edit-job-view/EditJobView.tsx, services/orchest-webserver/client/src/jobs-view/CreateJobDialog.tsx
Currently DataTable provides 5, 10, and 25 rows per page. This PR adds an extra option 100.
Fixes: #700
=> Add 100 rows per page option to DataTable

services/jupyter-server/start.sh
This PR removes the `--collaborative` flag when starting JupyterLab.
The flag seems to be the root cause of multiple issues we are seeing. Therefore we are removing it for the time being until it can be considered stable.
Resolves: #503, #725
Thank you @astrojuanlu for all the debugging :1st_place_medal:
=> Fix saving issues with JupyterLab

.github/workflows/integration-tests.yml
Why kill resources without using `orchest stop`?
- The command might be broken
- The command might not actually successfully kill all resources due to
incompatibility issues with the previous deployment
=> Don't rely on `orchest stop` to kill resources for integration tests

services/orchest-api/app/app/__init__.py, services/orchest-api/app/app/apis/namespace_environment_images.py, services/orchest-api/app/app/apis/namespace_pipelines.py, services/orchest-api/app/app/apis/namespace_projects.py, services/orchest-api/app/app/apis/namespace_sessions.py, services/orchest-api/app/cleanup.py, services/session-sidecar/app/main.py
~This PR makes it so that the `orchest-api` will perform the required cleanups on exit. This helps to maintain state consistent when it comes to shutting down, restarting or stopping Orchest.~
See https://github.com/orchest/orchest/pull/721#issuecomment-1053501770
=> Orchest-api rework cleanup as a command

deploy/orchest-ctl/pod.yml, orchest, services/orchest-ctl/app/cli/main.py, services/orchest-ctl/app/config.py, services/orchest-ctl/app/orchest/__init__.py, services/orchest-ctl/app/orchest/_core.py, services/orchest-ctl/app/orchest/_k8s_wrapper.py, services/orchest-ctl/app/orchest_old.py
Ports `orchest version` to k8s, and introduces a `--json` flag, e.g. `orchest version --json --ext`:
```json
{
"cluster_version": "v2022.02.8",
"deployment_versions": {
"argo-workflow-argo-workflows-server": "v3.2.6",
"argo-workflow-argo-workflows-workflow-controller": "v3.2.6",
"celery-worker": "latest",
"docker-registry": "2.7.1",
"file-manager": "latest",
"orchest-api": "latest",
"orchest-database": "13.1",
"orchest-webserver": "latest",
"rabbitmq-server": "3",
"update-server": "latest"
}
}
```
=> Orchest-ctl refactoring PR 2, `orchest version` 

services/orchest-webserver/client/src/routingConfig.tsx
Do not parse query string to lowercase
Parsing to lowercase would break opening files in JupyterLab through the
"EDIT IN JUPYTERLAB" button as it passes the filename as a query string.
Fuzzy filtering of the pipeline run table will not break as it itself
parses the given filter to lowercase (thanks @iannbing for mentioning
this case).
Fixes: #765
=> Fix opening files in JupyterLab that contain uppercase characters in their name

docs/source/fundamentals/configuration.rst, docs/source/fundamentals/data_passing.rst, docs/source/fundamentals/glossary.rst
Removes all memory-server related docs. The Kubernetes MVP won't have a memory-server and so we want to remove all user-facing content that mention it.
Related PR: #769
=> Remove memory-server related docs

services/orchest-ctl/app/cli/main.py, services/orchest-ctl/app/orchest/__init__.py, services/orchest-ctl/app/orchest/_core.py, services/orchest-ctl/app/orchest_old.py
Ports `orchest adduser` to k8s. The command is not completely tested given that it requires the `auth-server` to be running, which is currently not included in our deployment.
=> Orchest-ctl refactoring PR 5, `orchest adduser`

lib/python/orchest-internals/_orchest/internals/config.py, services/orchest-api/app/app/core/environment_image_builds.py, services/orchest-api/app/app/core/image_utils.py, services/orchest-api/app/app/core/jupyter_image_builds.py, services/orchest-api/app/app/core/tasks.py, services/orchest-api/app/config.py, services/orchest-ctl/app/utils.py, services/orchest-webserver/app/app/views/views.py
This PR contains some breaking changes, either reinstall through `orchest-ctl` or create the following directories: `/userdir/.orchest/env-img-builds`, `/userdir/.orchest/jupyter-img-builds`.
=> K8S move orchest directories to internal config

services/orchest-webserver/client/src/components/MainDrawer.tsx, services/orchest-webserver/client/src/pipeline-view/CreateNextStepButton.tsx
Currently if user is viewing the pipeline of a job run, the navigation item "Jobs", instead of "Pipelines", shouldn't be highlighted.
=> Fix highlighting navigation item "Jobs" when viewing the pipeline of a job run

services/orchest-webserver/client/src/pipeline-view/CreateNextStepButton.tsx, services/orchest-webserver/client/src/projects-view/ImportDialog.tsx
The regular expression for the import_url should take into account the trailing slash.
Fixes: #743
=> Fix not redirecting to Pipeline List after importing if the import URL contains trailing slash

services/orchest-api/app/app/__init__.py, services/orchest-api/app/app/apis/namespace_ctl.py, services/orchest-api/app/app/apis/namespace_environment_images.py, services/orchest-api/app/app/core/sessions/_manifests.py, services/orchest-api/app/app/schema.py, services/orchest-api/app/app/utils.py
Adds a couple of endpoints to provide to the `daemonset` in charge of pre pulling images what images should be pulled.
Endpoints:
- `/environment-images/latest` for a list of the latest environment images for every environment
- `ctl/orchest-images-to-pre-pull` for the list of orchest images to pre pull (i.e. session related)
Sessions will now make use of a customized jupyter-server image correctly.
=> daemonset pre pull images endpoints

services/orchest-webserver/client/src/contexts/ProjectsContext.tsx, services/orchest-webserver/client/src/hooks/useFetchPipelineJson.ts, services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx, services/orchest-webserver/client/src/pipeline-settings-view/common.ts, services/orchest-webserver/client/src/pipeline-settings-view/useFetchPipelineMetadata.ts, services/orchest-webserver/client/src/pipeline-settings-view/usePipelineEnvVariables.tsx, services/orchest-webserver/client/src/pipeline-settings-view/usePipelineProperty.tsx, services/orchest-webserver/client/src/pipeline-view/CreateNextStepButton.tsx, services/orchest-webserver/client/src/pipeline-view/PipelineActionButton.tsx, services/orchest-webserver/client/src/pipeline-view/ServicesMenu.tsx, services/orchest-webserver/client/src/types.d.ts
When editing Pipeline Settings, user loses their changes if they switch to other browser tabs and come back. This PR persists the changes as subsets of the whole Pipeline settings object. This PR also makes it possible to edit Pipeline Path in Pipeline Settings view. 
Fixes: #729, #770
=> Fix losing progress on Pipeline Settings when browser tab regaining focus

services/base-images/runnable-shared/runner/requirements-dev.txt, services/orchest-webserver/client/src/components/HeaderBar.tsx, services/orchest-webserver/client/src/components/MainDrawer.tsx, services/orchest-webserver/client/src/components/ProjectSelector.tsx, services/orchest-webserver/client/src/hooks/useMatchProjectRoot.ts, services/orchest-webserver/client/src/routingConfig.tsx
Currently Project Selector only appears in `/pipelines`, `/environments`, and `/jobs`, but not in the views at a deeper level, such as `/job`. It's very confusing especially when user have jobs/pipelines with the same name across projects. 
To make it clearer which project user is working on, this PR make ProjectSelector visible as long as the current view is within one project.
Current UI logic: if user switches projects while viewing "Jobs", the view stays at Jobs, e.g. from Project A Jobs -> Project B Jobs. This PR follows the same rationale, see the following example:
Viewing a job in project A, switch to project B, viewing the jobs of project B.
=> Show Project Selector in deeper levels of the UI

services/orchest-webserver/client/src/job-view/PipelineRunTable.tsx, services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx, services/orchest-webserver/client/src/pipeline-view/LogsView.tsx, services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx, services/orchest-webserver/client/src/pipeline-view/ServicesMenu.tsx, services/orchest-webserver/client/src/pipeline-view/contexts/PipelineEditorContext.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useIsReadOnly.tsx, services/orchest-webserver/client/src/pipeline-view/step-details/StepDetails.tsx, services/orchest-webserver/client/src/routingConfig.tsx, services/orchest-webserver/client/src/views/FilePreviewView.tsx, services/orchest-webserver/client/src/views/JobRunView.tsx
Currently `/pipeline` is used both for editing a pipeline and viewing a read-only pipeline of a job run. This causes quite a few bugs. For example, the root view while viewing a job run becomes `/pipelines`, where it should have been `/jobs`. And read-only state might be reset when user refreshes the page.
This PR creates a new route: `/job-run` and re-use the same component PipelineEditor. `/job-run` shows the pipeline always in the read-only mode, and its root view is `/jobs`. 
Edit: because this PR remove the unnecessary re-rendering. PipelineEditor in read-only mode has missing connection lines until first session polling response. Thus, this PR also fixes this issue.
=> Add route /job-run

services/orchest-webserver/client/src/hooks/useFetchPipelineJson.ts, services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx, services/orchest-webserver/client/src/pipeline-settings-view/useFetchPipelineMetadata.ts
Currently saving pipeline_json in Pipeline Editor is broken due to the temp uuid of services.
=> Fix the issue when saving services in pipeline editor

services/orchest-webserver/client/src/edit-job-view/EditJobView.tsx
Fix the bug that auto-clean-up cannot be disabled.
Fixes: #issue
=> Fix unable to disable auto-clean up in Edit Job view

services/node-agent/app/image_puller.py
The same image can be put on the queue multiple times and won't exist
yet on the system before its next occurrence in the queue is processed.
So we explicitly check whether we are not already pulling the image.
=> Do not pull images if they are already being pulled

deploy/helm/charts/postgres/templates/deployment.yaml, deploy/helm/charts/rabbitmq/templates/deployment.yaml
The rabbitmq and postgres volumes were not in userdir pvc
Fixes: #issue
=> move postgres and rabbitmq dir to userdir pvc

services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
When moving a folder while its files are also selected, it throws an error saying that the selected files do not exist. This is because those files are moved along with the folder already.
Solution: only execute the "moving the folder" operation and skip the operations on moving its offspring nodes.
Fixes: #838
=> Fix the error when moving a folder while its sub folders or files are also selected

services/auth-server/requirements.in, services/auth-server/requirements.txt, services/orchest-api/requirements.in, services/orchest-webserver/requirements.in, services/orchest-webserver/requirements.txt
After #843, some of the dependencies were not made explicit and accidental upgrades of problematic dependencies (recent releases of werkzeug and jinja2) sneaked in. This fixes it.
The culprit is using an unsupported Flask version by the way. But we can think about upgrading it at some other time.
Fixes: #issue
=> Make dependency pinnings explicit

services/orchest-api/app/app/utils.py, services/orchest-api/app/config.py
Allows increasing parallelism levels for jobs and interactive runs without restarting Orchest. Slightly refactors the `OrchestConfig` class.
=> Allow increasing jobs and interactive runs parallelism without restarting Orchest

services/node-agent/Dockerfile, services/node-agent/app/image_deleter.py, services/orchest-api/app/app/core/environments.py, services/orchest-api/app/app/core/registry.py
This PR introduces lifecycle management for orchest images. Images that are considered unused, due to their version not matching the current orchest deployment version, will be removed from nodes.
=> Automatically delete unused Orchest images from nodes

.github/workflows/ui.yml, lib/javascript/build-frontend.sh, lib/javascript/utils/src/fetcher.ts, lib/javascript/utils/src/index.ts, lib/javascript/utils/tsconfig.build.json, lib/javascript/utils/tsconfig.json, pnpm-lock.yaml, services/auth-server/client/tsconfig.build.json, services/auth-server/client/tsconfig.json, services/orchest-webserver/client/customTransformer.js, services/orchest-webserver/client/jest.config.js, services/orchest-webserver/client/jest.setup.js, services/orchest-webserver/client/package.json, services/orchest-webserver/client/src/__mocks__/handlers.mock.tsx, services/orchest-webserver/client/src/__mocks__/server.mock.tsx, services/orchest-webserver/client/src/contexts/ProjectsContext.tsx, services/orchest-webserver/client/src/contexts/__tests__/ProjectsContext.test.tsx, services/orchest-webserver/client/src/environment-edit-view/__tests__/useAutoSaveEnvironment.test.tsx, services/orchest-webserver/client/src/hooks/useFetchPipelines.ts, services/orchest-webserver/client/tsconfig.build.json, services/orchest-webserver/client/tsconfig.json, tsconfig.json
This PR adds tests on the logic of switching pipelines in `ProjectsContext`. These test cases could help ruling out the logic errors in the `ProjectsContext`.
This PR also sets up API mocking with [msw](https://mswjs.io/), so that we can test against the FE side of the integration.
=> Add jest tests to ProjectsContext

services/orchest-webserver/client/src/components/EnvironmentList.tsx, services/orchest-webserver/client/src/components/SessionToggleButton.tsx, services/orchest-webserver/client/src/contexts/SessionsContext.tsx, services/orchest-webserver/client/src/hooks/useSessionsPoller.ts, services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx
Session auto-start is not working as expected as it was designed to manage one session at a time. With the removal of `PipelinesView`, session auto-start should be triggered when changing pipeline (i.e. pipeline uuid).
=> Fix session not auto-started when changing pipeline in PipelineEditor

services/orchest-api/app/app/__init__.py, services/orchest-api/app/app/core/scheduler.py, services/orchest-api/app/app/models.py, services/orchest-api/app/migrations/versions/6bbe0b4a8c4a_.py
This is a preliminary PR to work on notifications, refactors the `orchest-api` scheduler to be consistent with the `orchest-webserver` scheduler implementation and makes it so that the database is used to keep track of tasks.
=> orchest-api scheduler keeps track of tasks in the database

services/orchest-webserver/client/src/components/ProjectBasedView.tsx, services/orchest-webserver/client/src/components/ProjectSelector.tsx, services/orchest-webserver/client/src/contexts/ProjectsContext.tsx, services/orchest-webserver/client/src/contexts/__tests__/ProjectsContext.test.tsx, services/orchest-webserver/client/src/hooks/useEnsureValidPipeline.tsx, services/orchest-webserver/client/src/jobs-view/JobsView.tsx, services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx, services/orchest-webserver/client/src/views/EnvironmentsView.tsx
Currently Orechest switches to an existing project if the given project UUID is invalid. This PR adds an alert if the said case occurs.
=> Add project-not-found error

services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
Fix failed to rename files in File Manager in Pipeline Editor.
=> Fix failed to rename files in File Manager

lib/javascript/utils/src/typed.ts, services/orchest-webserver/client/src/components/EnvVarList.tsx, services/orchest-webserver/client/src/components/ProjectSelector.tsx, services/orchest-webserver/client/src/components/SystemDialog.tsx, services/orchest-webserver/client/src/contexts/AppContext.tsx, services/orchest-webserver/client/src/hooks/useAsync.ts, services/orchest-webserver/client/src/hooks/useCancelablePromise.ts, services/orchest-webserver/client/src/hooks/useCancellablePromise.ts, services/orchest-webserver/client/src/hooks/useCustomRoute.ts, services/orchest-webserver/client/src/hooks/useOverflowListener.ts, services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx, services/orchest-webserver/client/src/pipeline-settings-view/ServiceForm.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContainer.tsx, services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsProperties.tsx, services/orchest-webserver/client/src/projects-view/EditProjectPathDialog.tsx, services/orchest-webserver/client/src/projects-view/ImportDialog.tsx, services/orchest-webserver/client/src/projects-view/common.tsx, services/orchest-webserver/client/src/utils/webserver-utils.ts, services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx, services/orchest-webserver/client/src/views/FilePreviewView.tsx, services/orchest-webserver/client/src/views/JupyterLabView.tsx, services/orchest-webserver/client/src/views/ProjectSettingsView.tsx, services/orchest-webserver/client/src/views/SettingsView.tsx, services/orchest-webserver/client/src/views/UpdateView.tsx
Combine the `makeCancelable` wrapper and `React.useEffect` as `useCancelablePromise`, which cancels the promise when unmounted automatically.
This PR also improves the usage of OverflowListener: call `unobserve` when unmount.
Cancelable fetch cannot be used in all cases. `useCancelablePromise` is a replacement of the old `PromiseManager`.
How you should use `PromiseManager`:
```ts
const promiseManager = React.useMemo(() => new PromiseManager(), [])
promiseManager.appendCancelablePromise(cancelablePromise);
let cancelablePromise = makeCancelable(
fetch("/async/something"),
promiseManager
);
fetchProjectsPromise.promise
.then(() => {
//....do things
})
React.useEffect(() => {
return () => promiseManager.cancelCancelablePromises();
}, []);
```
how you should use `useCancelablePromise`:
```ts …
```
=> Apply useCancelablePromise and useCancelableFetch

README.md, services/orchest-webserver/app/app/__init__.py, services/orchest-webserver/app/app/core/filemanager.py, services/orchest-webserver/app/app/core/pipelines.py, services/orchest-webserver/app/app/core/projects.py, services/orchest-webserver/app/app/error.py, services/orchest-webserver/app/app/utils.py, services/orchest-webserver/app/app/views/views.py
Related: https://github.com/orchest/orchest/pull/907
Fixes: https://github.com/orchest/orchest/issues/906
Credits to @porcupineyhairs for discovery and fix proposal
There are a couple of regressions on `dev` that make it not possible to test all edge cases, it's something we will have to look into next week.
=> Fix remove unsafe path joins

services/orchest-api/app/app/apis/namespace_jobs.py, services/orchest-api/app/app/apis/namespace_notifications.py, services/orchest-api/app/app/apis/namespace_projects.py, services/orchest-api/app/app/core/events.py, services/orchest-api/app/app/core/notifications/utils.py, services/orchest-api/app/app/core/notifications/webhooks.py, services/orchest-api/app/app/models.py, services/orchest-api/app/app/schema.py, services/orchest-api/app/migrations/versions/00ed420c6abf_.py, services/orchest-api/app/migrations/versions/7b9a23ad5946_.py, services/orchest-api/app/migrations/versions/dfe5c529e6da_.py, services/orchest-webserver/app/app/core/projects.py, services/orchest-webserver/app/app/views/views.py, services/orchest-webserver/client/src/job-view/JobStatus.tsx, services/orchest-webserver/client/src/types.d.ts
Part of of the notifications feature. Expands the content of webhook payloads, generally speaking, a payload event will carry the following information if applicable:
- project name and uuid
- job name, pipeline_name, uuid, next_scheduled_time, schedule, status (different properties based on cron-job vs one-off-job)
- cron-job run: run number, status, total number of runs
- job pipeline run: uuid, status, parameters, failed steps if any
Example payload:
```
{
"delivered_for": {
"content_type": "application/json",
"name": "string",
"subscriptions": [
{
"event_type": "project:one-off-job:created",
"job_uuid": null,
"project_uuid": null,
"subscriber_uuid": "d2dafc8b-fb5e-4c74-af3f-1d02643f3dad",
"uuid": "b111fd12-6535-4237-b090-da56f27c9db7"
},
{
"event_type": "project:cron-job:run:started", …
```
=> Expand webhook payload content

lib/javascript/utils/src/typed.ts, services/orchest-webserver/app/app/error.py, services/orchest-webserver/app/app/utils.py, services/orchest-webserver/app/app/views/views.py, services/orchest-webserver/client/src/hooks/useFetchPipelines.ts, services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx, services/orchest-webserver/client/src/pipeline-view/contexts/PipelineEditorContext.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/__tests__/getRelativePathTo.test.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useEventVars.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineCanvas.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/useGestureOnViewport.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/useKeyboardEventsOnViewport.tsx, services/orchest-webserver/client/src/pipeline-view/step-details/FilePicker.tsx, services/orchest-webserver/client/src/pipeline-view/step-details/ProjectFilePicker.tsx, services/orchest-webserver/client/src/utils/jquery-replacement.ts
Previously, only the project files can be assigned to pipeline steps. To encourage reusing generic scripts across projects, this PR allows user assign files in the `/data` folder to pipeline steps.
This PR also fixes the following bugs:
- When user uses the dropdown of the file picker to specify the file for pipeline steps, the value is the path should be relative to the pipeline file, instead of the project root.
- When user moves `.orchest` files from `Project files` to `/data`, it should not throw errors and the corresponding pipeline should be removed (i.e. disappear from the sessions panel).
- When user moves `.orchest` files from `/data` to `Project files`, the `.orchest` files should be recognized and added as pipelines (i.e. visible in the sessions panel).
@fruttasecca  Tag you …
=> Fix: allow assigning files in the `/data/` folder to pipeline steps

services/orchest-ctl/app/orchest/_core.py, services/orchest-webserver/client/src/hooks/useCheckUpdate.tsx, services/orchest-webserver/client/src/types.d.ts
This PR:
Once this PR is merged and `dev` is merged back into the controller branch the FE changes will have to be reverted, no BE changes are required since only `orchest-ctl` was modified, which won' be part of Orchest post controller release.
=> Disable updates for last pre-controller version

lib/python/orchest-internals/_orchest/internals/utils.py, orchest-sdk/python/orchest/pipeline.py, services/orchest-api/app/app/schema.py, services/orchest-api/app/app/types.py, services/orchest-webserver/app/app/compat.py, services/orchest-webserver/app/app/core/pipelines.py, services/orchest-webserver/app/app/views/views.py, services/orchest-webserver/client/src/contexts/AppContext.tsx, services/orchest-webserver/client/src/hooks/useFetchJob.ts, services/orchest-webserver/client/src/hooks/useFetchPipeline.ts, services/orchest-webserver/client/src/hooks/useFetchPipelineJson.ts, services/orchest-webserver/client/src/hooks/useFetchPipelineRun.ts, services/orchest-webserver/client/src/hooks/useFetchProject.ts, services/orchest-webserver/client/src/hooks/useFocusBrowserTab.ts, services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx, services/orchest-webserver/client/src/pipeline-settings-view/__tests__/useFetchPipelineSettings.test.tsx, services/orchest-webserver/client/src/pipeline-settings-view/common.ts, services/orchest-webserver/client/src/pipeline-settings-view/useFetchPipelineSettings.ts, services/orchest-webserver/client/src/pipeline-settings-view/usePipelineEnvVariables.tsx, services/orchest-webserver/client/src/pipeline-settings-view/usePipelineProperty.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContext.tsx, services/orchest-webserver/client/src/types.d.ts, services/orchest-webserver/client/src/utils/webserver-utils.ts
Currently services use user-defined `name` as the key for BE, and with this design, FE generates a FE-only property: `order` to ensure the consistency of the UI. This PR (re-)uses this property as the serial number of service.
This PR also fixes an unable-to-save issue in Pipeline Settings, and added more test cases.
=> Use `order` as the serial number for services

lib/python/orchest-internals/_orchest/internals/analytics.py, services/orchest-api/app/app/apis/namespace_environments.py, services/orchest-api/app/app/core/events.py, services/orchest-api/app/app/models.py, services/orchest-api/app/migrations/versions/19ce7297c194_.py
Part of the larger effort to add more events to the `orchest-api` and analytics.
=> Add environment created/delete events to `orchest-api` (notifications)

lib/python/orchest-internals/_orchest/internals/analytics.py, scripts/migration_manager.sh, services/orchest-api/app/app/apis/namespace_environments.py, services/orchest-api/app/app/apis/namespace_jobs.py, services/orchest-api/app/app/apis/namespace_pipelines.py, services/orchest-api/app/app/apis/namespace_projects.py, services/orchest-api/app/app/apis/namespace_runs.py, services/orchest-api/app/app/core/events.py, services/orchest-api/app/app/core/notifications/analytics.py, services/orchest-api/app/app/models.py, services/orchest-api/app/app/schema.py, services/orchest-api/app/app/types.py, services/orchest-api/app/app/utils.py, services/orchest-api/app/migrations/versions/19ce7297c194_.py, services/orchest-api/app/migrations/versions/23def7128481_.py, services/orchest-api/app/migrations/versions/268b3e08cb46_.py, services/orchest-api/app/migrations/versions/2b573339900f_.py, services/orchest-api/app/migrations/versions/637920f5715f_.py, services/orchest-api/app/migrations/versions/a4b1f48ddab5.py, services/orchest-api/app/migrations/versions/a863be01327d_.py, services/orchest-webserver/app/app/utils.py, services/orchest-webserver/app/app/views/orchest_api.py
Adds support for interactive pipeline run events in the `orchest-api`, these events can now be subscribed to and are now part of the analytics module.
=> Add  interactive pipeline run events to `orchest-api` (notifications)

services/orchest-webserver/client/src/App.tsx, services/orchest-webserver/client/src/contexts/AppContext.tsx, services/orchest-webserver/client/src/contexts/AppInnerContext.tsx, services/orchest-webserver/client/src/hooks/useCheckUpdate.tsx, services/orchest-webserver/client/src/hooks/useCustomRoute.ts, services/orchest-webserver/client/src/hooks/useFetcher.ts, services/orchest-webserver/client/src/hooks/useLocalStorage.ts, services/orchest-webserver/client/src/projects-view/ProjectsView.tsx, services/orchest-webserver/client/src/routingConfig.tsx, services/orchest-webserver/client/src/settings-view/SettingsView.tsx, services/orchest-webserver/client/src/settings-view/hooks/useOrchestVersion.tsx, services/orchest-webserver/client/src/views/HelpView.tsx
This is one of the PR's that removes the usage of swr (see #973).
Edit:
This ends up a rather-big refactoring. `useCheckUpdate` was moved to a new context `AppInnerContext`. The reason is that if `useCheckUpdate` lives inside a view, the polling is most likely won't be useful (user needs to stay in the same view for one hour to actually trigger the next check). To meet the requirement of the actual use case, we need to move `useCheckUpdate` to an app-wide context.
However, the existing `AppContext` cannot be used for this is that `useCheckUpdate` needs to detect route changes, so it needs to be wrapped as any child of `<Route />`, but `AppContext` must be a parent of `<Route /`>. So we run into a circular dependency.
Therefore, `AppInnerContext` was created. It's an app-wide context that …
=> Remove swr in useCheckUpdate

services/orchest-controller/deploy/thirdparty/argo-workflows/orchest-values.yaml, services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go
The default value, 10s, leads to a slow update of the status of steps for pipeline runs. Especially noticeable with steps that run quickly.
Fixes: #945
=> Lower default argo requeue time

services/orchest-webserver/client/src/contexts/AppContext.tsx, services/orchest-webserver/client/src/contexts/ProjectsContext.tsx, services/orchest-webserver/client/src/contexts/SessionsContext.tsx, services/orchest-webserver/client/src/hooks/useAsync.ts, services/orchest-webserver/client/src/pipeline-view/hooks/useEventVars.tsx, services/orchest-webserver/client/src/types.d.ts
setData in useAsync depends on `data`, which will cause indefinite re-rendering if the consumer put `setData` and `data` in the deps of React.useEffect.
This PR fixes it by remove `data` from the deps of `setData`.
The type ReducerActionWithCallback is to simplify typing of this pattern.
=> Fix useAsync setData causing indefinite re-rendering bug

services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContextMenu.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/TreeRow.tsx
It requires at least a pipeline to open a file in JupyterLab.
Fixes: #957
=> Disable opening file when the project has no pipeline

lib/python/orchest-internals/_orchest/internals/analytics.py, services/orchest-api/app/app/apis/namespace_environment_image_builds.py, services/orchest-api/app/app/core/events.py, services/orchest-api/app/app/core/notifications/analytics.py, services/orchest-api/app/app/models.py, services/orchest-api/app/app/utils.py, services/orchest-api/app/migrations/versions/0eaf40410361_.py, services/orchest-webserver/app/app/views/orchest_api.py
Part of the larger effort to add more events to the `orchest-api` and analytics.
=> Add environment image builds events to `orchest-api` (notifications)

services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
This PR removes an unnecessary  request when delete steps. The second request might overwrite the changes of the first request. Although I couldn't constantly reproduce issue #1020, this bug might be the most probable cause to it.
Fixes: #1020
checklist](https://github.com/orchest/orchest/blob/master/orchest-cli/RELEASE-CHECKLIST.md)
compatibility is maintained.
the corresponding `requirements.txt`.
=> Fix pipeline auto-saving when deleting steps

services/orchest-webserver/client/src/components/DataTable.tsx, services/orchest-webserver/client/src/hooks/useAsync.ts, services/orchest-webserver/client/src/hooks/useFetchPipelineJson.ts, services/orchest-webserver/client/src/hooks/useFetcher.ts, services/orchest-webserver/client/src/hooks/useSessionsPoller.ts, services/orchest-webserver/client/src/pipeline-view/hooks/useStepExecutionState.tsx
By default `useAsync` set `data` to `undefined` when fetching data. This causes UI flickering when polling, unless `caching` is set to `true`. Instead, it'd be easier to reverse it to `disableCaching` so that `useAsync` persists data by default. The consumer could decide to render `data` or not depending on `status`.
Fixes: #1021  
checklist](https://github.com/orchest/orchest/blob/master/orchest-cli/RELEASE-CHECKLIST.md)
compatibility is maintained.
the corresponding `requirements.txt`.
=> Fix UI flickering when polling

services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx, services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useContextMenu.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/useGestureOnViewport.tsx
Currently, `Zoom in` and `Zoom out` in the Context Menu assume the center point of the canvas as the center. 
This PR makes it so that it will zoom in/out precisely with the position of the Context Menu. 
This PR also fixes another minor issue:
When zoom in/out with pinching, the speed of zoom in/out is consistent; sometimes it becomes faster and faster (or slower and slower). This PR makes it consistent and smooth.
=> Use the position of the Context Menu as the center when zoom in & zoom out

README.md, docs/source/fundamentals/projects.rst
I was reading the documentation and encountered an incorrectly rendered bullet list. It's solved by adding a single space. As it's such a small change, feel free to close the PR and add it yourselves. I've build the docs locally to verify if the change is truly a fix.
Fixes: NA
=> Fixed a formatting error in `docs/fundamentals/projects.rst`

services/orchest-webserver/client/src/components/CommandPalette.tsx, services/orchest-webserver/client/src/hooks/useMatchProjectRoot.ts, services/orchest-webserver/client/src/routingConfig.tsx
This PR adds opening "Environments" and "Jobs" per project in the Command Palette. And also fix a minor bug: when user is viewing Environments of a project (i.e. `/environments?project_uuid=12345`), the page commands `Page: Environments` and `Page:Jobs` should open environments and jobs for project `12345` (currently it's broken because `project_uuid` is not passed into the command).
Fixes: #573
=> Add more commands to Command Palette

docs/requirements.txt, docs/source/conf.py
This is a continuation of the work from #1039 since it was reported that there were some tooltips that were showing empty content.
This commit will enable hoverxref on all the references of the documentation so we can debug it deeply and understand why there some cases where the content comes empty.
=> Docs: enable `sphinx-hoverxref` on all references

services/orchest-api/app/app/models/_core.py, services/orchest-api/app/app/schema.py, services/orchest-api/app/migrations/versions/3433a9040ff4_.py
A minor improvement to improve debugging
=> Keep track of pipeline runs creation time at the database level

services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useContextMenu.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
Extract PipelineEditorContextMenu from the hook, so that the hook only contains states, easier for unit testing.
Also some minor improvements:
- remove unnecessary state `contextMenuIsOpen` because context menu only requires `position`.
- remove `itemId` from the args of `ContextMenuItemAction`. Because itemId is contextual (e.g. stepUuid in PipelineStep), it should be part of implementation of the action function of menuItems, but not part of the args of the action function.
=> Extract PipelineEditorContextMenu from useContextMenu

services/orchest-webserver/client/src/pipeline-view/ServicesMenu.tsx
Show the running services that are exposed in the Services dropdown to improve clarity.
Fixes: #1070
=> Add "Not exposed" status in the services dropdown

services/orchest-api/app/config.py, services/orchest-api/start_celery_daemon.sh
Fix celery-worker bringup and image builder on arm64
=> Fix celery-worker bringup and image builder on arm64

services/orchest-api/app/app/apis/namespace_ctl.py, services/orchest-api/app/app/core/image_utils.py, services/orchest-api/app/app/core/scheduler.py, services/orchest-api/app/app/core/tasks.py, services/orchest-api/app/config.py
Adds an `orchest-api` level scheduler job that periodically cleanups the builder cache since it's (AFAIK) the only storage that user actions can't affect.
Opinion on adding an `orchest-api` endpoint that queues such a task? Even without a GUI button would be fine, just to know that we have at least a temporary solution for "power" users that need/want it to be cleaned up asap, might also prove useful for the cloud.
=> Periodically cleanup builder cache

docs/source/development/troubleshooting.rst
I had a similar issue as described in the Troubleshooting docs already, but I didn't have to build the Orchest docker image, so I never encountered the "Exit code 137" issue.
I changed it to be one example under a more generalized heading for the problem: minikube being unresponsive. It should still be searchable in the docs, and easily be indexed on Google. :)
Here is the rendered page: https://orchest--1091.org.readthedocs.build/en/1091/development/troubleshooting.html#minikube-is-unresponsive-on-docker-desktop
=> Improve section about bumping Docker Desktop resources

services/orchest-webserver/client/src/components/ParameterEditor.tsx
When user clicks on a parameter, the edit field (CodeMirror) should be focused.
Fixes: #431
=> Autofocus the parameter edit field in Job Edit view.

scripts/redeploy_branch.sh
If the remote branch is rebased, `git` will fail to pull. Deleting the local branch and re-fetch-and-pull from remote
would solve the problem.
=> Fix: a rebased branch cannot be re-deployed.

services/orchest-api/app/app/core/image_utils.py
This PR fixes the `pip-cache` warning during environment image building by `chown`ing the pip-cache to 1000/100 which is jovyan/users. The warning:
> WARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
The warning was observed when running on GKE.
=> Set correct permissions on `/pip-cache`

lib/python/orchest-internals/_orchest/internals/utils.py, services/orchest-api/app/app/core/sessions/_manifests.py, services/orchest-api/app/app/utils.py
This PR adds the image_puller manifest to jupyter-server and user-services if the image is not on global docker registries
=> Only use `image-puller` `initContainer` if `jupyter-server` is customized by user

services/orchest-webserver/app/app/views/orchest_api.py, services/orchest-webserver/client/src/components/BuildPendingDialog.tsx, services/orchest-webserver/client/src/components/SessionToggleButton.tsx, services/orchest-webserver/client/src/contexts/AppContext.tsx, services/orchest-webserver/client/src/contexts/ProjectsContext.tsx, services/orchest-webserver/client/src/contexts/SessionsContext.tsx, services/orchest-webserver/client/src/environments-view/common.tsx, services/orchest-webserver/client/src/hooks/useSessionsPoller.ts, services/orchest-webserver/client/src/job-view/JobView.tsx, services/orchest-webserver/client/src/jobs-view/JobList.tsx, services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx, services/orchest-webserver/client/src/pipeline-view/LogsView.tsx, services/orchest-webserver/client/src/pipeline-view/contexts/PipelineEditorContext.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/TreeItem.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useIsReadOnly.tsx, services/orchest-webserver/client/src/pipeline-view/sessions-panel/SessionsPanel.tsx, services/orchest-webserver/client/src/types.d.ts, services/orchest-webserver/client/src/utils/webserver-utils.ts, services/orchest-webserver/client/src/views/JupyterLabView.tsx
The implementation of SessionContext and `requestBuild` in AppContext has become obsolete and starts to become the bottleneck for building new features. This PR cleans up the legacy code for better performance and readability.
The changes are as follows:
- Convert the implementation of `requestBuild` from callbacks-based to promise-based, so no need to put callbacks in state.buildRequest.
- Move the code for `requestBuild` from `AppContext` to `ProjectsContext` because requestBuild only makes sense within a project.
- Convert state.sessions from an array to an object for better performance with less code.
- Replace `toggleSession` with `startSession` and `stopSession`.
=> Refactor SessionContext and AppContext.

services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx, services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx, services/orchest-webserver/client/src/pipeline-view/contexts/PipelineEditorContext.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useContextMenu.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
`onContextMenu` was interfered by `mouseup` event listeners, which causes the intended action was not fired and breaks the context menu. This PR fixes this issue by properly blocking the event listeners.
Fixes: #1108
=> Fix `Run selected steps` in the context menu not working issue.

services/orchest-api/app/app/core/sessions/_manifests.py, services/orchest-controller/pkg/controller/orchestcomponent/node_agent.go, services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go, services/orchest-controller/pkg/utils/k8s_utils.go
This PR passes the IngressClass name to `orchest-api` as an environment variable, so `orchest-api` can create an ingress resource with the correct class name so that it would be reachable.
Fixes: #1120
=> Pass detected ingress class name to orchest-api

services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx
Show a Snackbar if user chooses to stop all sessions in order to build JupyterLab. After all sessions are stopped, it will start to build JupyterLab automatically.
=> fix: show a Snackbar when stopping all sessions.

services/orchest-webserver/client/src/components/BuildPendingDialog.tsx, services/orchest-webserver/client/src/contexts/SessionsContext.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx
Currently, if JupyterLab is being built, visiting PipelineEditor will get an error about "JupyterEnvironmentBuildInProgress", which is not very user-friendly. This PR makes it so that it prompts an explanation, similar to the environment-images-build warning.
=> Show a proper warning in PipelineEditor if Jupyterlab is being built.

services/orchest-webserver/client/src/pipeline-view/hooks/useIsReadOnly.tsx
When the pipeline is viewed as a job run, it gets stuck in a read-only mode even if you browse back to the interactive pipeline. This PR fixes that.
https://www.loom.com/share/cbfd02356a3543d39c876d41f06e6ce2
=> Fix: Pipeline editor readonly after viewing job

services/orchest-webserver/client/src/contexts/ProjectsContext.tsx, services/orchest-webserver/client/src/pipeline-view/contexts/PipelineEditorContext.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useFetchInteractiveRun.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useInitializePipelineEditor.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useIsReadOnly.tsx, services/orchest-webserver/client/src/utils/webserver-utils.ts
When environment build is in progress, it shouldn't attempt to start a session, otherwise it will prompt an error, e.g. https://www.loom.com/share/cff42bbb98e64fa88660c281268fcc43.
This PR fixes this issue by setting read-only `true` as default and then set it to `false` if conditions met. So that it won't attempt to launch a session when view is just mounted.
=> Fix attempting to start a session when environment build in progress issue.

docs/requirements.txt, docs/source/conf.py
Add version warning for `latest` docs to minimize confusion.
This is how it looks like:
=> Add version warning for latest docs

services/orchest-controller/deploy/thirdparty/docker-registry/orchest-values.yaml, services/orchest-controller/pkg/addons/addons.go, services/orchest-controller/pkg/addons/helm_deployer.go, services/orchest-controller/pkg/addons/path_deployer.go, services/orchest-controller/pkg/controller/controller_utils.go, services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go, services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go, services/orchest-controller/pkg/controller/orchestcomponent/auth_server.go, services/orchest-controller/pkg/controller/orchestcomponent/celery_worker.go, services/orchest-controller/pkg/controller/orchestcomponent/component_utils.go, services/orchest-controller/pkg/controller/orchestcomponent/node_agent.go, services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go, services/orchest-controller/pkg/controller/orchestcomponent/orchest_database.go, services/orchest-controller/pkg/controller/orchestcomponent/orchest_webserver.go, services/orchest-controller/pkg/controller/orchestcomponent/rabbitmq_server.go, services/orchest-controller/pkg/helm/builder.go, services/orchest-controller/pkg/helm/helm.go, services/orchest-controller/pkg/utils/util.go
In this PR, the controller checks the deployed manifests of third parties with newly generated manifests and if they are not equal, it updates the helm releases. in this way even if we upgrade the helm templates of third parties, the controller still can update them.
Fixes: #1092
=> Update third-parties on Orchest update

docs/source/getting_started/faq.md
Document known ipykernel incompatibility.
Closes gh-425.
=> Document known ipykernel incompatibility

lib/python/orchest-internals/_orchest/internals/compat.py, services/orchest-api/app/app/__init__.py, services/orchest-webserver/app/app/core/pipelines.py, services/orchest-webserver/app/app/utils.py
This PR fixes the fact that jobs pipeline definitions aren't kept up to date when it comes to the pipeline definition schema. This would have caused issues if the `orchest-api` depended on the pipeline definition of a job being on the latest schema version after a change in the pipeline schema. This was discovered when trying to migrate a pre-k8s Orchest `orchest-api` database to the latest version.
Todos:
=> Keep jobs pipeline definitions up to date

utility-containers/image-puller/Dockerfile, utility-containers/image-puller/pull_image.sh
Fallbacks to using `buildah` to pull from the insecure internal registry and push to the docker daemon if pulling with docker fails, i.e. if we are in an environment or k8s flavor where docker won't pull from an insecure registry.
=> Fallback to buildah pull if docker pull fails

services/orchest-controller/pkg/addons/helm_deployer.go, services/orchest-controller/pkg/controller/controller_utils.go, services/orchest-controller/pkg/controller/orchestcluster/cluster_controller.go, services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go, services/orchest-controller/pkg/helm/helm.go
This issue fixes the problem in updating to v2022.07.6.
In v2022.07.6 we introduced assigning the IP address of the registry service, but if the registry already exists, and the assigned IP by k8s differs from our IP, k8s fails to update the registry.
Fixes: #issue
=> Use the IP of the existing registry service

package.json, services/auth-server/client/package.json, services/orchest-webserver/app/app/views/views.py, services/orchest-webserver/client/src/hooks/useCheckFileValidity.tsx, services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsContext.tsx, services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsProperties.tsx
I work on a project which involves non-developers, and thus step parameters per json is cumbersome. The idea to solve this is to describe the parameters per jsonschema and use this information to render a nice form to edit the step parameters.
The idea behind this feature: 
* use Jsonforms (https://jsonforms.io/) to render the input form for step parameters
* use per step sidecar file <stepfilename>.schema.json to provide parameter schema information
* use per step sidecar file <stepfilename>.uischema.json to provide further ui information
* schema files are optional (just no form without a schema.json)
* no read / execute of stepfile required to build form
* parameter raw json still visible and editable
The code behind the PR works but still has issues to iron out:
* jsonforms uses a ref …
=> Feature: Generate parameter forms from jsonschema

services/orchest-api/app/app/core/image_utils.py
This PR reduces the error surface of the image builer in an attempt to deal with https://github.com/orchest/orchest/issues/1171. This is also in view of the fact that the way we build images is likely to significantly change in an effort to improve performance.
=> Remove package managers builder cache

services/orchest-api/app/app/core/image_utils.py
Improves the way errors are handled during image builds by playing around an observed race condition where the container/pod status does not reflect the failure state yet. Essentially we check another time after the pod has reached an end state.
=> Improve race condition handling in image builds errors

services/orchest-webserver/client/src/components/ParameterEditor.tsx
From Slack:
Looks like there is an issue with the ParameterEditor component of the FE, to reproduce:
- create a pipeline with parameters
- create a job with some parameterized runs
- start the job
- go back to the job, open the parameters view
=> Fix app crashing when viewing parameters under some circumstances

services/orchest-api/app/app/apis/namespace_jobs.py, services/orchest-webserver/app/app/views/orchest_api.py, services/orchest-webserver/client/src/job-view/JobView.tsx
Adds an endpoint (and later some FE changes) to allow triggering a job run (a batch of pipeline runs) for jobs that are `PENDING|STARTED|PAUSED`. 
Fixes: #1181 
@yannickperrenet @ricklamers 
The BE is not very strict about requirements to trigger a job run, but I'm not sure about exposing a button for one-off.  jobs that are STARTED. Maybe it should be shown only for cronjobs which are `STARTED|PAUSED` and `PENDING` one-off jobs (one-off jobs scheduled in the future?). Also happy to make the BE more picky about the required state
=> Add endpoint to trigger a job run "manually"

services/orchest-webserver/Dockerfile
When building the webserver container, the following error appears:
```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies
services/orchest-webserver/client
├─┬ react-codemirror2 7.2.1
│ └── ✕ unmet peer react@">=15.5 <=16.x": found 17.0.2
└─┬ xterm-for-react 1.0.4
├── ✕ unmet peer react@^16.0.0: found 17.0.2
└── ✕ unmet peer react-dom@^16.0.0: found 17.0.2
```
This PR fixes that!
The core issue is that our `.npmrc` isn't copied into the container because it is at the root of the repo, and not at the root of the webserver project.
=> Fix: peer dependency issue when building web server

services/orchest-controller/deploy/thirdparty/argo-workflows/orchest-values.yaml, userdir/.gitignore, userdir/.orchest/database/.gitignore, userdir/.orchest/kernels/.gitignore, userdir/.orchest/rabbitmq-mnesia/.gitignore, userdir/.orchest/user-configurations/jupyterlab/.gitignore, userdir/.orchest/user-configurations/jupyterlab/lab/.gitignore, userdir/.orchest/user-configurations/jupyterlab/user-settings/.gitignore, userdir/README.md, userdir/data/.gitignore, userdir/jobs/.gitignore, userdir/projects/.gitignore
Removes Argo Server (we have never used but never disabled it) and `userdir` from the top-level repo directory (we dynamically create the structure in the app now).
=> Remove Argo Server

services/orchest-webserver/client/src/pipeline-view/ReadOnlyBanner.tsx
This should make it more convenient to navigate back to job runs.
The pipeline can still be navigate to using the "PIPELINES" menu item.
=> UI Overhaul: Change copy and action of "Job run snapshots"

services/orchest-webserver/client/src/components/ParameterEditorWithJsonForm.tsx, services/orchest-webserver/client/src/pipeline-view/step-details/StepParameters.tsx
`editableParameters` in `prettifyInputParameters` is not in sync with the latest value of editableParameters. Use setState callback to get the latest value. Also removed the unnecessary saving, as the value was already formatted and saved while typing. `onBlur` should only update the client-side state only.
Fixes: #1233
=> Fix unable to save pipeline parameters when clicking outside of the field.

services/orchest-api/app/app/core/image_utils.py
This PR disables the builder cache entirely as an attempt to circumvent https://github.com/orchest/orchest/issues/1171 for the time being, this is going to make image builds slower until https://github.com/orchest/orchest/pull/1198 is released, which will both speedup builds and fix #1171 by changing how images are built entirely.
Note: the pvc backing the builder cache will be removed in https://github.com/orchest/orchest/pull/1225
=> Disable builder cache

services/base-images/runnable-shared/runner/requirements-user.txt, services/jupyter-server/requirements.txt
Upgrade `jupyterlab_widgets` and future-proof ipywidgets for a working default experience.
Fixes: #1235.
=> Cap `ipywidgets` to avoid breakage

services/orchest-api/app/app/apis/namespace_jobs.py, services/orchest-api/app/app/schema.py, services/orchest-webserver/app/app/core/jobs.py, services/orchest-webserver/app/app/error.py, services/orchest-webserver/app/app/views/orchest_api.py
Allows altering the pipeline of a job which is still in the `DRAFT` status. Environment variables are resolved using the snapshotted state contained in the snapshot in use by the job. See the docstring of `_resolve_environment_variables` for more details.
@iannbing 
The functionality is exposed to the client through a new `orchest-webserver` endpoint, `/catch/api-proxy/api/jobs/<job_uuid>/pipeline` (PUT), which requires a json of the form `{"pipeline_uuid": "<uuid>"}` which indicates
which pipeline the job should be using. From the client POV the endpoint is a proxy to the `orchest-api` endpoint `/jobs/<job_uuid>/pipeline`, see the `orchest-api` swagger docs for the dos and don'ts.
Note that the `orchest-webserver` now also exposes the endpoint …
=> Dynamically update the pipeline of a job draft

services/orchest-webserver/client/src/api/job-runs/jobRunsApi.ts, services/orchest-webserver/client/src/api/job-runs/useJobRunsApi.ts, services/orchest-webserver/client/src/environments-view/EnvironmentMenuList.tsx, services/orchest-webserver/client/src/environments-view/common.tsx, services/orchest-webserver/client/src/environments-view/hooks/useSaveEnvironmentChanges.tsx, services/orchest-webserver/client/src/environments-view/hooks/useUpdateEnvironmentOnUnmount.tsx, services/orchest-webserver/client/src/hooks/useCurrentJobRun.ts, services/orchest-webserver/client/src/legacy-job-view/PipelineRunTable.tsx, services/orchest-webserver/client/src/pipeline-view/contexts/InteractiveRunsContext.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/PipelineCanvasHeaderBar.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/primary-action/CancelJobRunButton.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/primary-action/PrimaryPipelineButton.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/primary-action/RunPipelineButton.tsx, services/orchest-webserver/client/src/types.d.ts, services/orchest-webserver/client/src/utils/__tests__/array.test.ts, services/orchest-webserver/client/src/utils/array.ts, services/orchest-webserver/client/src/utils/record.ts
The primary purpose of this PR is to add a "Cancel Job Run" button to the pipeline editor when viewing a job run.
But I have also taken some time to create abstractions for the "job runs api" and a zustand store for it.
While doing so, I learned a lot about zustand, and because I found a lot of boilerplate code for array manipulation in other stores, I decided to create some helpers to reduce said boilerplate in this one.
=> UI Overhaul: Add cancel button to pipeline editor for job runs + zustand store

services/jupyter-server/Dockerfile, services/orchest-api/app/app/core/image_utils.py, services/orchest-api/app/app/core/jupyter_image_builds.py, utility-containers/image-builder-buildkit/Dockerfile, utility-containers/image-builder-buildx/Dockerfile
When using `buildah` to build images we could mount (RW) the jupyterlab settings from the builder to the container in which the build takes place, this is not possible anymore with `buildkit`. To circumvent that, the user settings are `rsync`'d from the container where the build takes place to the builder pod, which mounts the jupyter settings. 
To do that, a ssh server is started on the builder pod when building jupyter.
=> Write to JupyterLab user settings during custom Jupyter server build

lib/python/orchest-internals/_orchest/internals/config.py, services/node-agent/app/image_puller.py, services/node-agent/app/image_pusher.py, services/orchest-api/app/app/apis/namespace_ctl.py, services/orchest-api/app/app/apis/namespace_environment_images.py, services/orchest-api/app/app/apis/namespace_sessions.py, services/orchest-api/app/app/core/environments.py, services/orchest-api/app/app/core/sessions/_manifests.py, services/orchest-api/app/app/schema.py, services/orchest-api/app/app/utils.py, services/orchest-webserver/app/app/res/kernels/launch_kubernetes.py
Preliminary work needed for pod scheduling at the `orchest-api` level:
- have the `orchest-api` be notified of an image having been pulled to a node
- shift responsibility of kernels pod creation to orchest-api
=> Shift responsibility of kernels pod creation to `orchest-api`

services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/PipelineMoreOptionsMenu.tsx
I wasn't able to reproduce this issue before, because I didn't know that you could delete a pipeline from this location.
This PR ensures that the file tree is updated when the pipeline is deleted from the "more actions" context menu.
=> Update file tree when pipeline is deleted

services/orchest-webserver/client/src/components/common/EmptyState.tsx, services/orchest-webserver/client/src/environments-view/CreateEnvironmentButton.tsx, services/orchest-webserver/client/src/environments-view/EnvironmentMenuList.tsx, services/orchest-webserver/client/src/environments-view/EnvironmentMoreOptions.tsx, services/orchest-webserver/client/src/environments-view/edit-environment/EditEnvironmentContainer.tsx, services/orchest-webserver/client/src/environments-view/edit-environment/NoEnvironment.tsx, services/orchest-webserver/client/src/environments-view/hooks/useCreateEnvironment.tsx, services/orchest-webserver/client/src/environments-view/hooks/useSelectEnvironment.tsx, services/orchest-webserver/client/src/jobs-view/CreateJobButton.tsx, services/orchest-webserver/client/src/jobs-view/hooks/useCreateJob.tsx, services/orchest-webserver/client/src/jobs-view/job-view/NoJob.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/primary-action/usePipelineActions.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/NoPipeline.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/NoStep.tsx, services/orchest-webserver/client/src/pipeline-view/step-details/StepCreateEnvironmentButton.tsx, services/orchest-webserver/client/src/projects-view/NoProject.tsx
This PR adds empty state actions to the Jobs & environments view, and moves the common empty state components to `@/components/common/EmptyState.tsx`.
=> More empty state actions

services/orchest-webserver/client/src/environments-view/hooks/useCreateEnvironment.tsx
In the new UI, user could click "New environment" if there is no image with the matching language. However, currently, clicking on this button will crash the app.
=> fix: App crashed when creating an environment from PipelineEditor

services/orchest-webserver/client/src/api/jobs/jobsApi.ts, services/orchest-webserver/client/src/jobs-view/job-view/hooks/useJobActionMenu.tsx
Hide "Pause Job" and "Trigger a new Run now" options for a recurring job, as they are recurring-jobs-only features. This PR also set default `max_retained_pipeline_runs` to 250.
=> Fix/disable "Pause Job" and "Trigger a new Run now" for one-off jobs

docs/source/_static/js/installer_widget.js, services/orchest-controller/pkg/controller/orchestcomponent/buildkit_daemon.go
Required fix for Orchest `k3s` installations due to `k3s` using a dedicated `containerd` socket and storage by default.
=> Fix k3s support

services/orchest-webserver/client/src/jupyter/Jupyter.tsx, services/orchest-webserver/client/src/views/JupyterLabView.tsx
This PR fixes:
- The user gets "sucked back" into the JupyterLab view if the reload the page but quickly navigate away from it.
- "Setting up JupyterLab" flashes for a brief second if opening a file when JupyterLab has already been loaded
Additionally:
- Break out common functionality (like getting `_orchest_app`,  `_orchest_docmanager` and widgets) into shared functions
- Removes some unecessary `try`/`catch` blocks and instead doing using `?.` for dot-operations which they protected against.
Before JupyterLab has been initialized (first page load):
After JupyterLab has been initialized:
=> Fix: You get navigated back into JupyterLab on load

services/orchest-webserver/app/app/socketio_server.py, services/orchest-webserver/client/src/components/ImageBuildLog.tsx, services/orchest-webserver/client/src/components/legacy/LegacyImageBuildLog.tsx, services/orchest-webserver/client/src/pipeline-view/LogViewer.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useSocketIO.tsx
This PR adds `@socketio.on("disconnect", ...)` event handlers to `orchest-webserver` backend, and also creates a zustand store for socketio's to manage connections globally.
=> fix: Ensure websocket connections are closed correctly.

services/orchest-webserver/client/src/pipeline-view/contexts/PipelineDataContext.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx
@fruttasecca noticed that sometimes interactive sessions may get autostarted for job runs. This is not intended.
This PR changes so that sessions are never autostarted for job runs.
=> Don't autostart sessions for job runs

services/orchest-webserver/client/src/pipeline-view/file-manager/ActionBar.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useCreateStep.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
This PR unifies the FE logic of creating a step, and thus fixed the following bugs:
- When creating a file in `/data` folder and check "Create a step", the file assigned to the step is incorrect.
- When dropping a file to create a step, the `Step Name` should be auto-focused.
=> fix: Unable to create a file in /data folder

services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx
This PR fixes a regression: session doesn't auto start after environments finish building.
=> fix: session doesn't auto start after environments finish building.

services/orchest-webserver/client/src/pipeline-view/file-manager/FileManager.tsx
This PR makes it so that File Manager would attempt to fetch the file tree when project_uuid is changed.
=> fix: File Manager is not refreshed when switching to a project that doesn't have a pipeline.

services/orchest-webserver/client/src/jupyter/Jupyter.tsx, services/orchest-webserver/client/src/views/JupyterLabView.tsx
Had to make a few other changes in order to get this to work, as the error that we got was "Session already exists" (and not related to the session stopping). So I had to move this check to a separate `useEffect`, and it took some time to verify that there were no regressions.
Here it is, in all its glory!
=> Show dialog when session is stopping and you open JupyterLab

services/orchest-webserver/client/src/jobs-view/common.tsx
Some dates were displayed as UTC. This is because the server doesn't add "+00:00" to the end of the date string.
This is a quick hotfix in the front-end. Will investigate what can be done in the back-end.
=> Hotfix UTC dates without tz

services/orchest-webserver/client/src/api/jobs/useJobsApi.ts, services/orchest-webserver/client/src/jobs-view/hooks/useScheduleJob.tsx, services/orchest-webserver/client/src/jobs-view/job-view/hooks/useJobScheduleOption.tsx
If user doesn't change schedule after switching to another pipeline, the submitted schedule is empty (i.e. both `schedule` and `next_scheduled_time` are `null`). This PR ensures that the schedule is re-assigned right after switching pipelines of a draft job. This PR also remove the unnecessary sorting when creating a draft job.
=> Fix: draft job schedule is empty after switching to another pipeline

services/orchest-webserver/client/src/jobs-view/common.tsx, services/orchest-webserver/client/src/utils/date-time.ts
The datetime string from BE was invalid for Date.parse() on Safari. Adding the missing `T` fixes the issue.
=> fix: Jobs view crashes on Safari

services/orchest-webserver/client/src/environments-view/edit-environment/EditEnvironmentName.tsx, services/orchest-webserver/client/src/jobs-view/job-view/EditJobName.tsx, services/orchest-webserver/client/src/jobs-view/job-view/EditJobPipeline.tsx, services/orchest-webserver/client/src/jobs-view/job-view/EditJobProperties.tsx, services/orchest-webserver/client/src/jobs-view/job-view/JobView.tsx, services/orchest-webserver/client/src/pipeline-view/schedule-job/ScheduleJobPanel.tsx
From @ncspost's "nice-to-have" checklist:
=> Minor consistency tweaks for text inputs & properties

services/orchest-webserver/client/src/jobs-view/job-view/JobRunsTable.tsx
This PR adds a background color to chips in the job runs table:
=> ORC-908: Background color for chips in run table

services/orchest-webserver/client/src/components/BackToOrchestSettingsButton.tsx, services/orchest-webserver/client/src/hooks/useCheckUpdate.tsx, services/orchest-webserver/client/src/notification-settings-view/NotificationSettingsView.tsx, services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx, services/orchest-webserver/client/src/views/ManageUsersView.tsx, services/orchest-webserver/client/src/views/UpdateView.tsx
In Orchest settings view, some of the sub views don't have the "Back to settings" button.
=> Fix: add missing "back to settings" buttons

services/orchest-webserver/client/src/jobs-view/job-view/JobPrimaryButtons.tsx, services/orchest-webserver/client/src/jobs-view/job-view/hooks/useJobActions.tsx
This PR fixes two bugs: 
- After finishing editing a recurring job by clicking "SAVE JOB", user still gets a warning about "Unsaved progress" waring when navigating away.
- After clicking "Trigger job now", the JobRunTable doesn't show the new job run right away.
=> Fix: incorrect warning after saving a recurring Job.

services/orchest-controller/pkg/controller/orchestcomponent/orchest_webserver.go, services/orchest-webserver/app/app/__init__.py, services/orchest-webserver/app/scripts/log_streamer.py
Fixes an issue which would lead to having multiple `log_streamer` instances running thus duplicated logs. This can happen if the child of the PID1 gunicorn process dies, leaving the `log_streamer` process to be inherited by PID1. PID1 will start another instance of the application, leading to multiple `log_streamer`s.
Considered alternatives:
- using `prctl`, `subprocess.Popen(["sleep","10000"], preexec_fn=lambda : libc.prctl(1, signal.SIGKILL))`. 2nd favoured solution, I went with a separate container because it feels more native to k8s and decreases complexity, also considering that a webserver and `log-streamer` split will likely have to happen eventually
- checking in the `log_streamer` loop if the parent PID is 1, if so exit: felt like a breach of abstraction
Handwavy diagram
```
-> …
```
=> Move log-streamer to its own container in webserver pod

services/orchest-api/app/app/core/environment_image_builds.py
Similar to https://github.com/orchest/orchest/pull/731.
Improves performance.
=> Use `-exec ... +` notation for `find` to copy build context

services/node-agent/app/container_runtime.py, services/node-agent/app/image_deleter.py, services/node-agent/app/image_puller.py, services/node-agent/app/image_pusher.py
Makes it so that the `ContainerRuntime` class does not allow concurrent pushes or pulls of images. This has been done to reduce overhead and avoid some edge cases that have been observed, for example, multiple pushes through `buildah`.
I tried to go for the simplest solution, alternatives related to fiddling with the asyncio queue that holds images to pull or push (or other queues) felt a bit too risky for my tastes.
Also fixes a low impact bug where an image would be pulled multiple times in a row after being pulled successfully
=> Don't concurrently push or pull images

orchest-cli/orchestcli/cmds.py, services/orchest-api/app/app/connections.py
Adds retries to the k8s python SDK to reduce failures under system load.
To test, run this script after having killed the `kube-apiserver` container.
```
from kubernetes import client as k8s_client
from kubernetes import config
config.load_config()
from kubernetes.client.api_client import ApiClient
from kubernetes.client.configuration import Configuration
from urllib3.util.retry import Retry
def _get_k8s_api_client() -> ApiClient:
configuration = Configuration.get_default_copy()
_retry_strategy = Retry(
total=5,
backoff_factor=1,
)
configuration.retries = _retry_strategy
a= ApiClient(configuration=configuration)
return a
k8s_core_api = k8s_client.CoreV1Api(api_client=_get_k8s_api_client())
a = k8s_core_api.list_namespace()
print(len(a.items))
```
=> Add retries to k8s python sdk

services/orchest-webserver/client/src/projects-view/ProjectsTable.tsx
Fixes: [ORC-933](https://linear.app/orchest/issue/ORC-933/right-align-ellipses-menu-with-16px-margin-in-project-table-on)
=> Right align ellipsis menu in projects table

services/orchest-webserver/app/app/socketio_server.py, services/orchest-webserver/client/src/components/ImageBuildLog.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useSocketIO.tsx
Environment build logs sometimes failed to render because socket.io failed to reconnect immediately after being disconnected. This connect and disconnect is actually not necessary, as FE could just continue using the same connection. 
This PR made the following changes to remove the unnecessary disconnect:
- BE doesn't send logs on connect.
- FE sends a request to get logs when needed.
- FE doesn't disconnect until the browser tab is closed.
=> Fix: Environment build logs sometimes are failed to render.

services/orchest-controller/pkg/controller/orchestcomponent/celery_worker.go, services/orchest-controller/pkg/controller/orchestcomponent/orchest_api.go
Tweaks are based on recommendations of VPA whilst cluster was put CPU load either by a single threaded process and/or concurrently running jobs. In both scenarios Orchest should operate without issue, even on single-node.
https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
These changes should mitigate issues when the cluster is under load.
=> Tweak CPU resource requests

services/orchest-webserver/client/src/components/ImageBuildLog.tsx, services/orchest-webserver/client/src/environments-view/edit-environment/EnvironmentImageBuildLogs.tsx
When the browser tab loses and regains focus, Environment build logs are printed again.
This PR resets the logs when the browser tab loses focus.
=> Fix: Duplicated Environment build logs when switching browser tabs.

services/orchest-webserver/client/src/components/common/SnackBar.tsx, services/orchest-webserver/client/src/hooks/useHideIntercom.tsx, services/orchest-webserver/client/src/jobs-view/job-view/WebhookHint.tsx, services/orchest-webserver/client/src/pipeline-view/schedule-job/ScheduleJob.tsx, services/orchest-webserver/client/src/pipeline-view/schedule-job/ScheduleJobSnackBar.tsx, services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx
Intercom should be hidden when the side panel in Pipeline Editor or a bottom-right Snackbar appears.
=> fix: Hide Intercom when the side panel or a Snackbar appears.

services/orchest-webserver/client/src/environments-view/EnvironmentsView.tsx, services/orchest-webserver/client/src/jobs-view/JobsView.tsx
The header should be hidden if there's no item in the views of Environments and Jobs.
Fix: #1365
=> fix: Header should be hidden if no items available in Environments and Jobs

lib/python/orchest-internals/_orchest/internals/config.py, services/orchest-webserver/client/src/environments-view/edit-environment/hooks/useLoadSelectedBaseImage.tsx, services/orchest-webserver/client/src/environments-view/edit-environment/hooks/useSelectBaseImage.tsx
Fixes an issue where, unintentionally, the version of the base image was persisted in the environment properties. This led to the image being recognized as a custom image after an update despite being an Orchest base image.
=> Do not persist base image version by default

services/orchest-webserver/client/src/components/ImageBuildStatus.tsx, services/orchest-webserver/client/src/components/legacy/LegacyImageBuildLog.tsx, services/orchest-webserver/client/src/types.d.ts, services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx
When attempting to build JupyterLab image with active sessions, it should prompt user a warning with a call to action. This dialog doesn't appear due to some breaking changes on FE (i.e. FetchError refactor). This PR fixes this issue and add some type definitions.
Fixes: #1371
=> fix: Jupyter Image doesn't build if active sessions.

services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
Currently, if you zoom out and try to move a step, it tends to fly off the canvas.
https://user-images.githubusercontent.com/8259221/195647000-63370e4e-62b6-4771-8c65-c65c0882cc3e.mp4
This is because the scaling is applied to the final position, and not just the mouse delta.
=> Fix bad step offset being set when zoomed out and moving steps

services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx, services/orchest-webserver/client/src/pipeline-view/hooks/useInteractiveRuns.tsx, services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx
The warning dialog should be replaced by a custom dialog stating "A JupyterLab environment build is in progress. You can cancel to view the pipeline in read-only mode." 
Fixes: #1381
=> Fix: Wrong dialog when visiting PipelineEditor while JupyterLab is building.

services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx, services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/hooks/useViewportKeyboardEvents.tsx
If you open a pipeline editor where the steps are located close to `[0, 0]` in the canvas, the read-only banner covers them, which is undesired:
This PR fixes that so that the starting position is offset when the banner is showing. If the user hasn't moved away from the starting position when the banner goes away, the offset is also automatically removed.
This offset triggers on any read-only state in the editor, so it automatically supports all banners.
=> Offset pipeline starting position if read-only banner is showing

services/orchest-api/app/app/core/sessions/_manifests.py
Allows uploading files of any size through the JupyterLab file manager. Adding Y&N as reviewers to notify of the change.
Fixes: #1236
=> Remove body size limit from jupyter server ingress

services/orchest-webserver/client/src/pipeline-view/file-manager/CreateFileDialog.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/CreateFolderDialog.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/FileManager.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContext.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx, services/orchest-webserver/client/src/utils/path.ts
Currently, it is not possible to manage files in Orchest below the third sub-directory—we never load that far. 
https://user-images.githubusercontent.com/8259221/196445243-194b3750-3291-4c5f-8235-56bfcc0f2d21.mp4
This PR fixes so that …
- Expanding seemingly empty directories in the file tree also attempts to load them
- Reloading the file browser reloads everything up until the deepest expanded level
Resulting in …
https://user-images.githubusercontent.com/8259221/196445322-bac56a86-b456-489a-a394-fb1ed8b2821e.mp4
=> Fix: The file tree can't be expanded beyond the third level

services/orchest-webserver/client/src/projects-view/ProjectsTable.tsx
The ID of the Project data table should be Project UUID instead of its path.
Fixes: #1386
=> fix: Incorrect warning bout "Project doesn't exist"

services/orchest-webserver/client/src/contexts/ProjectsContext.tsx
When environment images are building, the pop-up warning is redundant. This PR removes this dialog.
=> fix: Redundant warning about Environment building in progress.

services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx
Using `/` instead would make users believe they need to enter an absolute path, which actually won't work.
=> Set empty string as default file path when creating new step

docs/source/_static/js/installer_widget.js, docs/source/getting_started/installation.md
Change installation targets in docs. We're deprecating macOS and Windows based installations. From now on we offer the free Orchest Cloud hosted version and offer documentation and support on installing Orchest on Linux through `minikube` or on managed k8s with flavors `EKS` and `GKE` (AWS/GCP).
=> Change installation docs.

services/orchest-webserver/app/scripts/background_tasks.py, services/orchest-webserver/client/src/projects-view/ImportDialog.tsx, services/orchest-webserver/client/src/projects-view/hooks/useImportGitRepo.ts, services/orchest-webserver/client/src/utils/webserver-utils.ts
Properly handle `git clone` (e.g. specifying a private repo URL) failures during Project import:
https://user-images.githubusercontent.com/26223174/197776080-2245b982-d7c3-474d-b7d1-1c42b590733d.mp4
=> Fail Project import if repo couldn't be `clone`d

services/orchest-webserver/client/src/components/EnvVarInput.tsx, services/orchest-webserver/client/src/components/EnvVarList.tsx, services/orchest-webserver/client/src/jobs-view/job-view/EditJobEnvVariables.tsx, services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx, services/orchest-webserver/client/src/pipeline-settings-view/ServiceForm.tsx, services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
This PR makes all environment variables "secret" by default, meaning you have to click a "reveal" button to make them visible. However, if the value of the variable is empty; the input is automatically revealed as this makes it more convenient to enter a value.
https://user-images.githubusercontent.com/8259221/199490076-a3b83b01-f0cc-4cb9-91bc-2cd41d3f38c7.mp4
I decided to create a new component called `EnvVarInput` to more easily encapsulate the "revealed" state and some logic around that.
Fixes: #679
=> Make environment variables "secret" by default

services/orchest-webserver/client/src/header-bar/HeaderBar.tsx, services/orchest-webserver/client/src/header-bar/SessionStatus.tsx, services/orchest-webserver/client/src/hooks/useSessionsPoller.ts
This PR removes the "Unable to fetch sessions" error dialog, in favor of a snackbar message that is less intrusive. This snackbar is only displayed after a few initial attempts to fetch sessions have failed and is only displayed in the "Pipelines" and "JupyterLab" views, where it is relevant.
https://user-images.githubusercontent.com/8259221/200020531-8bc768ec-0f76-498c-978d-890954281614.mp4
The logic for which the snackbar is displayed is this:
- Nothing is displayed if it succeeds in getting the session status under five tries (~5 seconds).
- We start displaying the spinner if it fails more than five times
- We display the error message if it fails more than 180 times (~3 minutes).
- The user likely has to do some intervention here. There is probably something wrong with the instance.
- …
=> Replace "Unable to fetch sessions" alert with unintrusive snackbar message

services/orchest-webserver/client/src/components/common/SnackBar.tsx, services/orchest-webserver/client/src/header-bar/SessionStatus.tsx, services/orchest-webserver/client/src/jobs-view/job-view/WebhookHint.tsx, services/orchest-webserver/client/src/pipeline-view/schedule-job/ScheduleJobSnackBar.tsx, services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx
For #1409 @ncspost mentioned that "the best position for Snackbars is the center for Orchest". So this PR changes that.
The `Snackbar` component will now (by default) be displayed in the bottom center of the app.
This also means that we don't have to hide the Intercom-button in the general case.
=> Move all Snackbar message to bottom center.

services/orchest-webserver/client/src/pipeline-settings-view/ServiceForm.tsx
Currently, clicking on a service causes the page to go blank, this is due to a bad rename from #1406.
=> Fix can't view service under pipeline settings

services/orchest-webserver/client/src/api/files/fileApi.ts, services/orchest-webserver/client/src/api/files/useFileApi.ts, services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContextMenu.tsx
When duplicating a file, the file tree is not currently updated with the new duplicated file after it succeeds.
=> Update file tree when duplicating a file

services/orchest-webserver/client/src/components/layout/MainSidePanel.tsx, services/orchest-webserver/client/src/components/layout/stores/useLayoutStore.tsx, services/orchest-webserver/client/src/pipeline-view/schedule-job/ScheduleJobPanel.tsx, services/orchest-webserver/client/src/pipeline-view/step-details/StepDetails.tsx
Currently, the max width for the side panels/drawers is based on the initial window width (when the page is loaded) and is never updated.
=> Fix: Make sure panel max width is based on current window width

services/orchest-webserver/client/src/components/ParameterEditorWithJsonForm.tsx, services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx, services/orchest-webserver/client/src/pipeline-settings-view/__tests__/usePipelineSettings.test.tsx, services/orchest-webserver/client/src/pipeline-settings-view/hooks/useFetchPipelineSettingsData.tsx, services/orchest-webserver/client/src/pipeline-settings-view/hooks/usePipelineSettings.tsx
The changes of Pipeline params got overwritten if user continue editing the pipeline without execute a pipeline run. This PR fixes this issue by updated the central states in PipelineDataContext when Pipeline params are changed in Pipeline Settings.
Fixes: #1430
=> fix: Pipeline params got overwritten after closing Pipeline Settings panel.

services/orchest-api/app/app/core/sessions/_manifests.py
The request would otherwise fail since the port name is required when a service has more than one port.
=> Create a port name for each user service port

services/orchest-webserver/app/app/views/views.py
Currently `/async/file-management/read` allows the client to cache. This is causing issues that client doesn't get prompt updates about the file changes.
Fixes: #1270
=> fix: the response of FM read shouldn't be cached.

services/orchest-webserver/client/src/components/SessionToggleButton.tsx
This PR removes the disabled state from the session toggle buttons while sessions are starting, allowing you to stop sessions before they are started.
=> Support stopping starting sessions

services/orchest-api/app/app/__init__.py, services/orchest-api/app/app/apis/namespace_ctl.py, services/orchest-api/app/app/core/scheduler.py, services/orchest-api/app/app/utils.py
Adds a hidden setting that allows pausing Orchest, when Orchest is paused the job scheduler will not run. The PR is rather low calories, no abstractions were introduced to match the fact that the setting is hidden (it's simply removed before returning the settings), imo it's premature until we do not know where we are going with this "feature"
=> Add setting to pause Orchest

docs/requirements.txt, docs/source/conf.py
Addresses (hopefully) https://github.com/orchest/orchest/issues/1445. It's a workaround and doesn't go to the root cause, but this has been difficult to reproduce in some environments so it's a quick solution.
Continuation of gh-1446 with the correct branch name.
=> Pin pydata-sphinx-theme to avoid accessibility issue

services/orchest-api/app/app/apis/namespace_jobs.py
Tightens the query (although the filters are now slightly overlapping assuming `next_scheduled_time` is always updated correctly) in order to avoid an incorrect state affecting the result of the endpoint. One use case is limiting the damage of the inconsistent state that could have been created in releases prior to this race condition fix: https://github.com/orchest/orchest/commit/9b7eefeb2c2908329466b0407c75ec3a39603fde
=> Only consider `PENDING|STARTED` jobs for the `next_scheduled_job` query/endpoint

services/orchest-webserver/client/src/components/SessionToggleButton.tsx, services/orchest-webserver/client/src/pipeline-view/sessions-panel/SessionsPanel.tsx
Without these, it is hard to know whether the session is ready:
https://user-images.githubusercontent.com/8259221/204787059-bc3ea45c-b742-4194-ae09-995ec571bdd9.mp4
=> Add starting/stopping indicators in sessions panel

services/orchest-api/app/app/core/pod_scheduling.py
Before deciding on where to schedule pods the `orchest-api` will check with the k8s api what's the state of the nodes of the cluster, which avoids scheduling pods on nodes that have been removed from the cluster or are not considered ready.
=> Detect cluster nodes readiness when scheduling pods

.pre-commit-config.yaml
Update flake8 URL to avoid `fatal: could not read Username for 'https://gitlab.com/': No such device or address` (see for example https://github.com/orchest/orchest/actions/runs/3603114378/jobs/6070903616#step:6:66)
=> Update flake8 URL

services/orchest-webserver/client/src/settings-view/SettingsView.tsx
Above 2TB available storage:
Below 2TB available storage:
This handles the EFS storage case (no hard upper limit) more gracefully.
=> Just show disk used for very large available GB sizes

services/orchest-webserver/client/src/jobs-view/job-view/EditJobParameters.tsx
Sometimes the wrong job parameters show up in the UI: this PR fixes that.
It is a pure rendering problem: the back-end & backing state is fine.
The source of the issue seems to be an optimization to only re-render the form if the pipeline has changed _and_ if any parameters are specified. The problem with that is:
- The parameters may change depending on multiple reasons: project, job, or pipeline (and possibly something else).
- Having no parameters is a perfectly valid state: we should render that.
This caused the UI to behave erratically when jumping between jobs & pipelines: displaying the wrong parameters and names.
=> Fix job parameter rendering issues

services/orchest-webserver/app/app/views/views.py
`file_path` is a positional (not named) argument now:
https://github.com/pallets/flask/issues/4753
=> Fix: schemas not loading

services/orchest-webserver/client/src/pipeline-view/file-preview/StepPipelineSelector.tsx
When clicking "open" in the step pipeline selector, you end up at the jobs page if you're at the pipelines page, and the pipelines page if you're on the job page.
=> Fix bad "open" link next to pipeline selector

services/orchest-webserver/client/src/pipeline-view/file-manager/FileManager.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx, services/orchest-webserver/client/src/pipeline-view/file-manager/FileTreeRow.tsx
It currently isn't possible to open files by double-clicking in the file browser. In short, this is because our `onSelect` and `onDoubleClick` handlers are "fighting each other", since they both cause a navigation.
This PR changes so that the "click to preview" reacts to `onClick` instead of `onNodeSelect`, and sets up a more lenient double-click handler alongside the default double-click handler to capture more clicks and provide more granular control over click behavior.
=> Fix double-click issues in the file browser

services/orchest-webserver/client/src/api/environments/useEnvironmentsApi.ts, services/orchest-webserver/client/src/environments-view/EnvironmentMenuList.tsx, services/orchest-webserver/client/src/environments-view/hooks/useFetchBuildStatus.tsx, services/orchest-webserver/client/src/types.d.ts, services/orchest-webserver/client/src/utils/record.ts
In /environments, when the browser tab regains focus, `fetchAll` is called to keep the environment list up-to-date, but `fetchAll` also washes away the current UI state (i.e. `lastBuild`), and thus the build state is then only re-stored in the next round of polling. This PR persists `lastBuild` so the UI state is persisted.
=> Fix: losing environment build status when switching browser tabs

services/node-agent/app/container_runtime.py
This effectively makes `list_images` behave equally for both docker and containerd, and makes it work as documented by the docstring in the docker case. The filter brought in the assumption that all images that are of interest for the caller of `list_images` should have the "Orchest" maintainer label, but that's not the case when an environment has been built with a custom base image.
The returned images affected the downstream logic of the `node-agent` of removing unused images from the node, making it so that unused images of environments built with custom images would not be deleted.
=> Remove unnecessary filter when listing images on node using docker container runtime

services/orchest-webserver/client/src/App.tsx, services/orchest-webserver/client/src/api/system-config/orchestConfigsApi.ts, services/orchest-webserver/client/src/api/system-config/useOrchestConfigsApi.ts, services/orchest-webserver/client/src/contexts/GlobalContext.tsx, services/orchest-webserver/client/src/contexts/Intercom.tsx, services/orchest-webserver/client/src/contexts/Providers.tsx, services/orchest-webserver/client/src/environments-view/edit-environment/CustomImageDetails.tsx, services/orchest-webserver/client/src/environments-view/edit-environment/EnvironmentImageBuildLogs.tsx, services/orchest-webserver/client/src/environments-view/hooks/useCreateEnvironment.tsx, services/orchest-webserver/client/src/header-bar/HeaderBar.tsx, services/orchest-webserver/client/src/hooks/useFetchOrchestConfigs.ts, services/orchest-webserver/client/src/hooks/useHideIntercom.tsx, services/orchest-webserver/client/src/hooks/useInitIntercom.ts, services/orchest-webserver/client/src/hooks/useOnAppStart.ts, services/orchest-webserver/client/src/hooks/useOpenReplay.ts, services/orchest-webserver/client/src/hooks/useSendAnalyticEvent.ts, services/orchest-webserver/client/src/jobs-view/job-view/hooks/useParameterReservedKey.tsx, services/orchest-webserver/client/src/settings-view/SettingsView.tsx, services/orchest-webserver/client/src/types.d.ts, services/orchest-webserver/client/src/views/ConfigureJupyterLabView.tsx, services/orchest-webserver/client/src/views/HelpView.tsx
Move the fetching Orchest config mechanism from GlobalContext to a zustand store.
After this refactor, GlobalContext is side-effect-free, which is easier for further clean-up.
The side effects such as initialize Intercom and OpenReplay were moved to `useOnAppStart`.
=> Move Orchest configs to a zustand store

services/orchest-api/app/app/core/pod_scheduling.py, services/orchest-api/app/app/core/sessions/_manifests.py
Fixes an issue where scheduling pods on the control plane wouldn't be done if the logic didn't get past some checks, e.g. the output of `_should_constrain_to_nodes_with_image`
=> Fix workers plane scheduling

services/orchest-webserver/client/src/routingConfig.tsx
When going to "settings" or "help" page, the app redirects you to the fallback project, and displays it in the project selector.
These are not project-scoped pages, so they should not do that.
=> Don't redirect to or display "project" on settings/help

services/orchest-api/app/app/__init__.py, services/orchest-api/app/app/apis/namespace_environment_image_builds.py, services/orchest-api/app/app/apis/namespace_git_imports.py, services/orchest-api/app/app/apis/namespace_jobs.py, services/orchest-api/app/app/apis/namespace_jupyter_image_builds.py, services/orchest-api/app/app/apis/namespace_runs.py, services/orchest-api/app/app/core/scheduler.py, services/orchest-api/app/app/core/tasks.py, services/orchest-api/app/app/utils.py
Fixes a memory leak that happened when creating an instance of celery before sending a task, I've simply made it so that celery is instanced only once, although according to the [docs](https://docs.celeryq.dev/en/stable/userguide/application.html) it should have been safe not to do so.
=> Create the celery app only once

services/auth-server/app/app/views.py
Fixes: fixes an issue where auth sessions not yet expired couldn't set the git config or ssh keys in the settings.
=> Expire sessions that don't have up to date cookies

services/orchest-api/app/app/apis/namespace_jobs.py, services/orchest-webserver/client/src/components/common/SystemStatusIcon.tsx, services/orchest-webserver/client/src/components/pipeline-runs/PipelineRunRow.tsx, services/orchest-webserver/client/src/components/pipeline-runs/PipelineRunsTable.tsx, services/orchest-webserver/client/src/home-view/AllRunsTab.tsx, services/orchest-webserver/client/src/home-view/utils/filter.ts, services/orchest-webserver/client/src/hooks/useCustomRoute.ts, services/orchest-webserver/client/src/jobs-view/job-view/JobRuns.tsx, services/orchest-webserver/client/src/types.d.ts, services/orchest-webserver/client/src/utils/system-status.ts
- Adds the view link back to the job runs table. This time after the status (for alignment purposes).
- Fixes some alignment issues for "Started time" in the table
- Fixes so pending interactive runs are included in All Runs
- Fixes "open in new tab" when there are important query parameters
- Fixes sort order in job runs table
... and some minor other fixes (see commits).
=> Add "view" link back to job runs, fix sort order and "open in new tab"
