orchest/orchest

lib/python/orchest-internals/_orchest/internals/config.py
orchest/orchest-api/app/app/core/pipelines.py
orchest/orchest-api/app/app/core/sessions.py
orchest/orchest-api/app/app/core/tasks.py
orchest/orchest-api/app/app/schema.py
orchest/orchest-webserver/app/app/res/kernels/launch_docker.py

This should work around the issues in https://github.com/orchest/orchest/issues/29

Use docker volumes for the memory-server socket

---

lib/python/orchest-internals/_orchest/internals/config.py
orchest-sdk/python/orchest/config.py
orchest-sdk/python/orchest/datasources.py
orchest-sdk/python/orchest/errors.py
scripts/build_container.sh
services/file-manager/.docker.json
services/file-manager/Dockerfile
services/file-manager/static/custom.css
services/nginx-proxy/orchest.conf
services/orchest-api/app/app/core/pipelines.py
services/orchest-ctl/app/cmdline.py
services/orchest-ctl/app/config.py
services/orchest-webserver/app/app/__init__.py
services/orchest-webserver/app/app/kernel_manager.py
services/orchest-webserver/app/app/res/kernels/launch_docker.py
services/orchest-webserver/app/app/templates/base.html
services/orchest-webserver/app/app/views.py
services/orchest-webserver/app/static/js/main.js
services/orchest-webserver/app/static/js/views/DataSourcesView.js
services/orchest-webserver/app/static/js/views/FileManagerView.js
userdir/data/.gitignore

File manager service is based on the excellent https://github.com/filebrowser/filebrowser project.

Add new feature: file manager

---

lib/python/orchest-internals/_orchest/internals/utils.py
orchest-sdk/python/orchest/datasources.py
services/orchest-webserver/app/app/res/kernels/launch_docker.py

Do not prohibit kernels from starting when a data source of type "Filesystem directory" points to an invalid path.

Hotfix datasource mounts

---

README.md
docs/source/user_guide/data_passing.rst
docs/source/user_guide/other.rst
services/orchest-webserver/app/app/analytics.py
services/orchest-webserver/app/static/js/views/EnvironmentEditView.js
services/orchest-webserver/app/static/js/views/PipelineSettingsView.js
services/orchest-webserver/app/static/js/views/PipelineView.js

This is nothing more than a collection of minor changes.

Multiple minor changes

---

docs/source/getting_started/installation.rst
docs/source/getting_started/overview.rst
docs/source/user_guide/environments.rst

The Installation guide for Orchest is a bit hard to follow as a first time user, so wanted to clean it up a little bit to make it easier for people to get started. I also think most people will need to get some sort of environment setup, so I reordered it to be at the top of the Overview index.

Make docs more readable and easy to understand

---

.gitignore

Updates `.gitignore` to include artifacts created during the build process. These files don't exist once build has been completed, but it helps to avoid confusion for new contributors.

Add build artifacts to .gitignore

---

services/orchest-api/app/app/apis/namespace_validations.py
services/orchest-webserver/client/src/components/BuildPendingDialog.jsx
services/orchest-webserver/client/src/main.tsx

Handle build failure on gate check

---

docs/source/user_guide/sdk/python.rst

Small change to reflect changes to the Orchest Python SDK when working with parameters.

[docs] Small change to reflect changes to the Orchest Python SDK when working with parameters

---

package.json
services/auth-server/Dockerfile
services/orchest-webserver/Dockerfile
services/orchest-webserver/client/src/hooks/orchest/provider.jsx
services/orchest-webserver/client/src/hooks/orchest/sessions.jsx
services/orchest-webserver/client/src/types.d.ts
services/orchest-webserver/client/src/views/ConfigureJupyterLabView.jsx
services/orchest-webserver/client/src/views/JupyterLabView.jsx

- bumps pnpm to a version that fixes common Vite bugs
- Fixes the Jupyter configure view behaviour

Upgrade pnpm and add sessionsKillAll

---

lib/design-system/package/src/core/global.ts
services/jupyter-server/Dockerfile
services/jupyter-server/requirements.txt
services/jupyter-server/start.sh

This PR increments the JupyterLab version to add support for real-time collaboration in JupyterLab :partying_face:
Incredible work by the JupyterLab / Yjs team.

Increase JupyterLab version to add real-time collaboration

---

services/orchest-ctl/app/docker_wrapper.py

Small PR to take care of a rare race condition where `orchest-ctl` would attempt to remove a container that is already being removed.

Improve orchest-ctl container removal

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/improvement.md
README.md

Add issue templates to the repo to ensure requirements are fully gathered ahead of work

Update issue templates

---

services/orchest-webserver/app/app/utils.py
services/orchest-webserver/app/app/views/views.py
services/orchest-webserver/client/src/components/EnvironmentList.jsx
services/orchest-webserver/client/src/components/JobList.jsx
services/orchest-webserver/client/src/components/PipelineList.jsx
services/orchest-webserver/client/src/views/ProjectsView.jsx

Handle removed projects.

---

docs/source/user_guide/environment_variables.rst

Removed an incorrect duplicate word from the docs.

Remove a duplicate word

---

.github/workflows/pre-commit.yml
package.json

- Runs build and adds lint step (which was skipped)
- Fixes an issue that @fruttasecca identified where certain modules weren't found (e.g. the design system which wasn't in `lib`)

Extend Pre-commit Steps

---

services/orchest-webserver/client/src/views/EnvironmentsView.jsx
services/orchest-webserver/client/src/views/FileManagerView.jsx
services/orchest-webserver/client/src/views/HelpView.jsx
services/orchest-webserver/client/src/views/JobsView.jsx
services/orchest-webserver/client/src/views/ManageUsersView.jsx
services/orchest-webserver/client/src/views/PipelinesView.jsx

Partial implementation of https://github.com/orchest/orchest/issues/259, migrating components to "Functional" style

Functional Components

---

docs/source/developer_guide/development_workflow.rst

Adding direction to install Docker in linux environment to set development environment.

Docker install in dev environment

---

services/orchest-webserver/app/app/views/views.py
services/orchest-webserver/client/src/components/PipelineList.jsx

Fixes #255

---

services/orchest-webserver/client/src/components/CronScheduleInput.jsx
services/orchest-webserver/client/src/components/DateTimeInput.jsx
services/orchest-webserver/client/src/views/JobView.jsx

Fix scheduled jobs timezone mismatch

---

services/orchest-ctl/app/orchest.py
services/orchest-ctl/tests/test_orchestapp.py

Verify version consistency on update and install

---

services/orchest-webserver/client/src/views/PipelineView.jsx

Fix deselecting after drag selecting zero steps

---

services/orchest-webserver/client/src/views/PipelineView.jsx

Fixes #270

---

services/orchest-webserver/client/src/views/PipelineView.jsx

Based on the status of the session the messaging should change.
For example:

Improve user message when trying to open step in JupyterLab

---

services/orchest-webserver/client/src/components/PipelineStep.jsx

Change pipeline step time duration formatting: "11161 sec." to "3h 6m 1s".
Closes #303.

Format seconds nicer (esp. for longer durations)

---

lib/design-system/package/CHANGELOG.md
lib/design-system/package/package.json
lib/design-system/package/src/icons/index.tsx
lib/design-system/package/src/logos/index.tsx
pnpm-lock.yaml

Creates a new release for the Design System – for consumption in private projects.

Design System Release

---

services/orchest-api/app/app/models.py

This PR silences a warning related to relationships pointing to the same table, see the newly committed comment for more context.

Add overlaps to Pipeline model relationships

---

services/orchest-webserver/client/src/App.tsx
services/orchest-webserver/client/src/components/AlertDialog.jsx
services/orchest-webserver/client/src/components/BuildPendingDialog.jsx
services/orchest-webserver/client/src/components/ConfirmDialog.jsx
services/orchest-webserver/client/src/components/Dialogs.jsx
services/orchest-webserver/client/src/components/EnvironmentList.jsx
services/orchest-webserver/client/src/components/ProjectSelector.jsx
services/orchest-webserver/client/src/components/ServiceForm.jsx
services/orchest-webserver/client/src/views/JobView.jsx
services/orchest-webserver/client/src/views/JupyterLabView.jsx
services/orchest-webserver/client/src/views/LogsView.jsx
services/orchest-webserver/client/src/views/PipelineSettingsView.jsx
services/orchest-webserver/client/src/views/UpdateView.jsx

Fix RefManager and PromiseManager in functional components

Fix RefManager and PromiseManager in functional components

---

services/orchest-webserver/client/src/views/PipelineSettingsView.jsx

Fix saving of pipeline parameters

---

services/orchest-ctl/app/orchest.py
services/orchest-webserver/client/src/components/Layout/OnboardingDialog/OnboardingDialogCarousel/use-onboarding-dialog-carousel.js
services/orchest-webserver/client/src/components/Layout/OnboardingDialog/use-onboarding-dialog.js
services/orchest-webserver/client/src/views/PipelineSettingsView.jsx

* Fixes: #362
* Improved Orchest start time

v2021.06.8

---

docs/source/developer_guide/development_workflow.rst

Improving the development docs with a troubleshooting section. The first item is about schema changes breaking Orchest when moving between branches.

Improve development troubleshooting docs

---

services/orchest-ctl/app/cli/main.py
services/orchest-ctl/app/orchest.py

Note that the `--rm` option requires the use of `--wait`.

Add '--rm' option to CLI run command

---

docs/source/developer_guide/development_workflow.rst
docs/source/user_guide/jobs.rst
lib/design-system/package/src/components/dialog.tsx
lib/javascript/mdc/src/MDCButtonReact.jsx
lib/python/orchest-internals/_orchest/internals/config.py
services/orchest-api/app/app/__init__.py
services/orchest-api/app/app/apis/namespace_jobs.py
services/orchest-api/app/app/apis/namespace_validations.py
services/orchest-api/app/app/core/environment_builds.py
services/orchest-api/app/app/core/tasks.py
services/orchest-api/app/app/models.py
services/orchest-api/app/app/utils.py
services/orchest-api/app/migrations/versions/8feeb577ca3f_.py
services/orchest-api/app/tests/namespaces/conftest.py
services/orchest-api/app/tests/namespaces/test_namespace_jobs.py
services/orchest-api/app/tests/namespaces/test_namespace_projects.py
services/orchest-ctl/app/cli/main.py
services/orchest-ctl/app/config.py
services/orchest-ctl/app/docker_wrapper.py
services/orchest-ctl/app/orchest.py
services/orchest-ctl/tests/test_orchestapp.py
services/orchest-webserver/app/app/core/pipelines.py
services/orchest-webserver/client/src/components/BuildPendingDialog.jsx
services/orchest-webserver/client/src/components/EnvironmentList.jsx
services/orchest-webserver/client/src/components/JobList.jsx
services/orchest-webserver/client/src/styles/main.scss
services/orchest-webserver/client/src/views/EditJobView.jsx

- Improved job consistency with respect to environments (see #361 for details).
- Fixed an edge case where running jobs were affected when updating Orchest.

v2021.07.1

---

.github/workflows/integration-tests.yml

Improvements to the integration tests action.

Improvements to the integration tests action

---

services/orchest-webserver/client/src/views/EditJobView.tsx

Validate cron string before running job

---

cypress/support/commands.ts
docs/source/developer_guide/testing.rst
docs/source/index.rst

Add Testing Guidelines

---

services/orchest-webserver/app/app/__init__.py
services/orchest-webserver/app/app/analytics.py
services/orchest-webserver/app/app/views/analytics.py
services/orchest-webserver/app/app/views/orchest_api.py
services/orchest-webserver/app/app/views/views.py
services/orchest-webserver/client/src/App.tsx

This PR introduces changes to our analytics module so that all data passes through the same logic, ensuring that we can easily work with the data thanks to the common structure. Additionally, the new implementation provides (inside the `_Anonymizer` class) an extensive overview of all the events that we support.
Structure always in the following format:
```
{
"event_properties": ...  # anonymized event properties
"derived_properties": ...  # derived from removed properties
"app_properties": ...  # Orchest application properties
}
```
1. `./orchest start --log-level=DEBUG`
2. Trigger some events
3. Check the `docker logs orchest-webserver` and note entries such as `Successfully sent analytics event 'session start'`.
In addition I checked the PostHog data to make sure entries are created.

Improve analytics data structure

---

services/orchest-webserver/app/app/views/views.py

Fixes an issue that was introduced in #378 . The issue is related to fetching the job json definition instead of the specific job run pipeline definition.

Fix job runs pipeline json retrieval

---

README.md

I have added my profile in contribution section in `README.md` as I am beta testing the app. 
Fixes: #issue

Adding my Icon in contribution

---

services/orchest-webserver/client/src/views/PipelineView.tsx

Fix "H" key capture in PipelineView

---

README.md
docs/source/getting_started/quickstart.rst
docs/source/index.rst

Update positioning in docs and README.

Update positioning in docs and README

---

services/orchest-api/app/app/apis/namespace_runs.py
services/orchest-api/app/app/errors.py
services/orchest-api/app/app/utils.py
services/orchest-webserver/app/app/utils.py

Fixes: #310 
For reference, from the issue:
> The pipeline editor can then handle the fact that no environment is defined.
is not yet implemented. Just like before it will show an error dialog, but this time the error message is improved instead of bubbling up Docker internals.

Remove environment from pipeline definition on environment delete

---

services/orchest-webserver/app/app/core/projects.py

Fix filesystem project discovery

---

services/orchest-webserver/client/src/styles/main.scss
services/orchest-webserver/client/src/views/PipelineSettingsView.tsx

Add tooltip to the memory eviction option in the pipeline settings

---

services/orchest-webserver/client/src/pipeline-view/PipelineDetailsProperties.tsx
services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx

Fixes an issue where a step kernel would be overwritten with incomplete data in some edge cases, such as:
- fixing the step for an environment which step does not exist in the project
- changing the kernel of a step

Fix step kernel change

---

.github/workflows/close_pr_issues.yml
scripts/close_associated_issues.py

Because we use git-flow and a default branch of `master` we can not make use of issue linking in PRs... which is pretty annoying in my opinion. The added workflow in this PR parses the PR body and closes the mentioned issues on successful merge of the PR.
Syntax:
```
Fixes: #<issue-number>, #<another-issue>, ...
```

Close linked issues automatically on PR merge

---

services/orchest-webserver/client/src/views/EditJobView.tsx

Correctly handle job name changes

---

services/orchest-webserver/client/src/pipeline-view/PipelineDetailsProperties.tsx
services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx
services/orchest-webserver/client/src/views/PipelineSettingsView.tsx

Change step properties update semantics to replace and merge.
Fixes: https://github.com/orchest/orchest/issues/492

Change step properties update semantics to replace and merge.

---

services/orchest-webserver/client/src/hooks/orchest/sessions.tsx

v2021.09.9

---

services/orchest-webserver/client/src/components/ProjectSelector.tsx

Hot fix release, fixes navigation error.

v2021.11.4

---

services/orchest-api/app/app/apis/namespace_jobs.py
services/orchest-api/app/app/schema.py
services/orchest-webserver/client/src/views/JobView.tsx

Fix job duplication behavior

---

services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx

Add offset to new step creation preventing exact overlap

---

services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx
services/orchest-webserver/client/src/utils/pipeline-layout.ts
services/orchest-webserver/client/src/utils/webserver-utils.ts

Fixes: #567 
Also adds an offset so that steps are not placed behind the top buttons ("NEW STEP" etc).

Fix edge cases for auto-align button

---

services/orchest-api/app/app/apis/namespace_jobs.py
services/orchest-api/app/tests/namespaces/test_namespace_jobs.py

Add endpoint to cancel a job pipeline run

---

services/base-images/base-kernel-julia/Dockerfile
services/base-images/base-kernel-py-gpu/Dockerfile
services/base-images/base-kernel-py/Dockerfile
services/base-images/base-kernel-r/Dockerfile
services/base-images/runnable-shared/bootscript.sh
services/base-images/runnable-shared/runner/run.py

Make it easier for users to install another Python version.
I will add an example to the docs on the `improv/docs` branch :+1:

Add `CONDA_ENV` to specify conda environment to use in runner

---

services/base-images/base-kernel-julia/Dockerfile
services/base-images/base-kernel-py-gpu/Dockerfile
services/base-images/base-kernel-py/Dockerfile
services/base-images/base-kernel-r/Dockerfile

`conda run` should not be used in production.

Remove `conda run` usage

---

lib/python/orchest-internals/_orchest/internals/utils.py
services/orchest-webserver/app/app/__init__.py

Hotfix release, unrelated to the previous release.

Release v2021.12.3

---

services/orchest-webserver/app/app/analytics.py

Adds a `system_properties` entry to analytics events, which will include OS information and if GPU is enabled.
Also adds `MAX_INTERACTIVE_RUNS_PARALLELISM` and `MAX_JOB_RUNS_PARALLELISM`  to the existing `app_properties`.

analytics system properties

---

cypress/cypress/integration/file-system-interactions.spec.ts
services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx

`interactive-run.spec.ts` fails after `cy.reload()` because user could already attempt to press "NEW STEP" when `state.pipelineJson` is not yet loaded. Thus, the action button should only be rendered when `state.pipelineJson` is provided.

hide buttons if state.pipelineJson is undefined

---

services/orchest-api/app/app/apis/namespace_jobs.py
services/orchest-api/app/app/schema.py
services/orchest-api/app/tests/namespaces/test_namespace_jobs.py

Related to #596, to be merged after the FE has moved to the new endpoint.

Do not fetch pipeline runs when fetching a job

---

services/orchest-api/app/app/apis/namespace_jobs.py
services/orchest-api/app/app/schema.py
services/orchest-api/app/tests/namespaces/test_namespace_jobs.py

Revert "Do not fetch pipeline runs when fetching a job"

---

services/orchest-webserver/app/app/analytics.py

Count file type usage in pipeline to give insight on e.g. usage of notebooks vs Python scripts.

Count file type usage in pipeline

---

services/base-images/base-kernel-julia/Dockerfile
services/base-images/base-kernel-py-gpu/Dockerfile
services/base-images/base-kernel-py/Dockerfile
services/base-images/base-kernel-r/Dockerfile

Set default renderer to fix plotly plots in JupyterLab

---

cypress/cypress/support/commands.ts
lib/javascript/utils/src/fetcher.ts
services/orchest-webserver/app/app/core/pipelines.py
services/orchest-webserver/app/app/views/views.py
services/orchest-webserver/client/src/components/HeaderBar.tsx
services/orchest-webserver/client/src/contexts/ProjectsContext.tsx
services/orchest-webserver/client/src/pipelines-view/CreatePipelineDialog.tsx
services/orchest-webserver/client/src/pipelines-view/PipelineList.tsx
services/orchest-webserver/client/src/projects-view/CreateProjectDialog.tsx
services/orchest-webserver/client/src/projects-view/EditProjectPathDialog.tsx
services/orchest-webserver/client/src/projects-view/ProjectsView.tsx
services/orchest-webserver/client/src/projects-view/common.tsx
services/orchest-webserver/client/src/projects-view/hooks/useFetchProjects.ts
services/orchest-webserver/client/src/projects-view/hooks/useImportProject.ts
services/orchest-webserver/client/src/projects-view/hooks/useProjectName.ts
services/orchest-webserver/client/src/types.d.ts

#639 go to pipelines after creating project

---

services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx
services/orchest-webserver/client/src/pipeline-view/ServicesMenu.tsx
services/orchest-webserver/client/src/pipeline-view/useAutoStartSession.ts

Services were not shown when there is a running session in Pipeline Editor. This PR also fixes an issue: an unnecessary session auto start is triggered in Pipeline Editor.
Fixes: #issue

Show service list correctly in PipelineView

---

services/orchest-api/app/app/core/sessions/_core.py
services/orchest-api/app/app/core/sessions/_manifests.py
services/session-sidecar/app/main.py

Piggybacking on some existing code in the branch to add permissions to the session sidecar to read pod logs.

Add session sidecar RBAC resources

---

services/auth-server/app/app/views.py
services/auth-server/client/src/styles/main.scss
services/auth-server/client/src/views/Login.tsx

This improves security as the attacker won't get additional information, e.g. whether a username actually exists or not.

Always return identical error message on invalid login credentials

---

services/jupyter-server/requirements.txt

Release notes: https://github.com/jupyterlab/jupyterlab/releases/tag/v3.3.0

Upgrade JupyterLab to `v3.3.0`

---

docs/source/fundamentals/environments.rst
services/base-images/base-kernel-julia/Dockerfile
services/base-images/base-kernel-py-gpu/Dockerfile
services/base-images/base-kernel-py/Dockerfile
services/base-images/base-kernel-r/Dockerfile

Document conda as a supported installer, with its caveats.
Fixes: #759

Add mention to conda in the documentation

---

services/orchest-api/app/app/apis/namespace_ctl.py
services/orchest-webserver/app/app/views/views.py

Add restart to webserver & api ctl namespace

---

services/orchest-api/app/app/apis/namespace_ctl.py
services/orchest-webserver/app/app/views/views.py

Minor fixes

---

services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx

Currently zoom-in/out in Pipeline Editor is not working.

Fix zoom-in/out issue

---

services/orchest-webserver/client/src/components/Layout/OnboardingDialog/OnboardingDialog.tsx
services/orchest-webserver/client/src/components/Layout/OnboardingDialog/use-onboarding-dialog.ts

When import URL is an empty string, it should redirect to quickstart project

Fix onboarding redirect to quickstart issue

---

deploy/Makefile

This PR waits for cert-manager deployments readiness

wait for cert-manager readiness

---

services/orchest-webserver/client/src/components/ServiceForm.tsx
services/orchest-webserver/client/src/environment-edit-view/ContainerImagesRadioGroup.tsx
services/orchest-webserver/client/src/environment-edit-view/CustomImageDialog.tsx
services/orchest-webserver/client/src/environment-edit-view/common.tsx
services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
services/orchest-webserver/client/src/pipeline-view/ServicesMenu.tsx
services/orchest-webserver/client/src/utils/webserver-utils.ts

- Hide/disable GPU options for the time being.
- add `Exposed` column to the Service Table 
- only render exposed services in the Services Menu in Pipeline Editor

FE changes to cope with k8s

---

orchest
services/orchest-ctl/app/cli/main.py
services/orchest-ctl/app/config.py
services/orchest-ctl/app/orchest/__init__.py
services/orchest-ctl/app/orchest/_core.py

Adds a minimal `orchest uninstall` command.

Add orchest uninstall command

---

services/orchest-webserver/client/src/components/Layout/OnboardingDialog/OnboardingDialog.tsx
services/orchest-webserver/client/src/components/Layout/OnboardingDialog/use-onboarding-dialog.ts
services/orchest-webserver/client/src/contexts/AppContext.tsx

Currently the onboarding dialog is not open when clicking "Show Onboarding" button in Help view.

Fix showing onboarding dialog in help view

---

lib/design-system/package/package.json
pnpm-lock.yaml
services/auth-server/client/package.json
services/orchest-webserver/client/package.json
services/orchest-webserver/client/src/main.tsx
services/orchest-webserver/client/src/pipeline-view/ConnectionDot.tsx
services/orchest-webserver/client/src/pipeline-view/PipelineEditor.tsx
services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
services/orchest-webserver/client/src/pipeline-view/hooks/useEventVars.tsx
services/orchest-webserver/client/src/pipeline-view/pipeline-connection/PipelineConnection.tsx
services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewport.tsx
services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/useGestureOnViewport.tsx
services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/useKeyboardEventsOnViewport.tsx
services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/useMouseEventsOnViewport.tsx
services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/useZoomOnViewport.tsx

This PR enables user to make better use of a touchpad.
- two-finger moving to pan the canvas
- pinch to zoom in/out the canvas
The existing behaviors remain:
- mouse wheel up/down to zoom in/out the canvas
- mouse primary key down and drag to pan
Fixes: #648

Enable panning and pinching on Pipeline Editor

---

deploy/Makefile

This PR sets the storage size of registry to 999Ti

set pvc size of registry to 999Ti

---

services/orchest-webserver/client/src/pipeline-settings-view/useFetchPipelineSettings.ts

User might lose progress in Pipeline settings when switching browser tabs. This issue was a regression introduced earlier in version [v2022.04.1](https://github.com/orchest/orchest/releases/tag/v2022.04.1).

Fix losing progress pipeline settings when switching browser tabs

---

services/orchest-webserver/client/src/routingConfig.tsx
services/orchest-webserver/client/src/views/ProjectSettingsView.tsx

Route "pipelines" is replaced by "pipeline".

Fix broken Project Settings view

---

services/orchest-webserver/app/app/views/views.py
services/orchest-webserver/client/src/hooks/useFetchPipelineJson.ts
services/orchest-webserver/client/src/utils/webserver-utils.ts
services/orchest-webserver/client/src/views/FilePreviewView.tsx
services/orchest-webserver/client/src/views/JupyterLabView.tsx

Fix the issue that Configure Jupyter Lab view does not load if the setup script is never saved.

Fix Configure Jupyter Lab view not loading issue

---

services/orchest-webserver/client/src/contexts/__tests__/ProjectsContext.test.tsx
services/orchest-webserver/client/src/pipeline-settings-view/__tests__/useFetchPipelineSettings.test.tsx

This test was implemented before the mock data generator PR. This PR fixes them in the `dev` branch.

Fix failing tests for ProjectsContext.test.tsx

---

services/orchest-webserver/client/src/components/ProjectSelector.tsx
services/orchest-webserver/client/src/hooks/use-interval.ts
services/orchest-webserver/client/src/hooks/useEnsureValidPipeline.tsx
services/orchest-webserver/client/src/hooks/useFetchPipelineJson.ts
services/orchest-webserver/client/src/jupyter/Jupyter.tsx
services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContainer.tsx
services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx
services/orchest-webserver/client/src/pipeline-view/hooks/useOpenNoteBook.tsx
services/orchest-webserver/client/src/projects-view/ProjectsView.tsx
services/orchest-webserver/client/src/views/JupyterLabView.tsx

Fix the bug: when opening JupyterLab it immediately redirects back to PipelineEditor, and other issues including:
- uploaded files via File Manager were uploaded again
- All files in `/data` folder shouldn't be allowed to open

Fix JupyterLab not loading issue and other small issues.

---

deploy/helm/charts/celery-worker/templates/deployment.yaml
services/orchest-api/Dockerfile_celery
services/orchest-api/app/app/core/notifications/__init__.py
services/orchest-api/app/app/core/notifications/webhooks.py
services/orchest-api/app/app/core/scheduler.py
services/orchest-api/app/app/core/tasks.py
services/orchest-api/app/app/models.py
services/orchest-api/app/config.py
services/orchest-api/celery_daemon_configs/worker_deliveries.conf

Add recurring task to process deliveries

---

services/orchest-controller/deploy-controller/deployment.yaml

No-op release for internal testing purposes.

Release v2022.05.3

---

services/orchest-webserver/client/src/components/ImageBuildLog.tsx
services/orchest-webserver/client/src/environment-edit-view/EnvironmentEditView.tsx

When building Environment images, the building logs were printed multiple times. This PR fixes this bug.

Fix socket.on called multiple times issue

---

services/jupyter-server/requirements.in
services/jupyter-server/requirements.txt

[Release announcement](https://discourse.jupyter.org/t/jupyterlab-3-4-0-is-released/14106?u=astrojuanlu), [complete changelog](https://github.com/jupyterlab/jupyterlab/releases/tag/v3.4.0).
Personal highlights:
New cell toolbar
"New tab" button

Upgrade JupyterLab to `v3.4`

---

services/orchest-api/app/app/apis/namespace_projects.py
services/orchest-webserver/client/src/views/ProjectSettingsView.tsx

In Project Settings, updating env variables was broken.

Fix unable to update project env variables issue.

---

docs/source/development/development_workflow.rst
docs/source/fragments/regular-installation.rst
docs/source/getting_started/installation.rst

Linearizes development instructions so they are easier to follow.
Fixes: #issue
checklist](https://github.com/orchest/orchest/blob/master/orchest-cli/RELEASE-CHECKLIST.md)
compatibility is maintained.
the corresponding `requirements.txt`.

Linearize development instructions

---

services/auth-server/app/app/views.py
services/auth-server/client/src/views/Admin.tsx

Prevent logged in user from deleting own account

---

services/orchest-webserver/client/src/App.tsx
services/orchest-webserver/client/src/components/CommandPalette.tsx
services/orchest-webserver/client/src/hooks/useHotKeys.ts
services/orchest-webserver/client/src/jupyter/Jupyter.tsx

Fix issue: Command Palette is not callable in JupyterLab view

---

lib/python/orchest-internals/_orchest/internals/analytics.py
services/orchest-webserver/app/app/views/orchest_api.py
services/orchest-webserver/app/app/views/views.py

Minor PR to improve the consistency of the payload schema of telemetry events sent by the webserver.

Improve consistency of `orchest-webserver` telemetry events

---

docs/source/development/feature_manuals.rst
docs/source/index.rst
lib/python/orchest-internals/_orchest/internals/analytics.py
services/orchest-api/app/app/models/_events.py
services/orchest-webserver/app/app/views/orchest_api.py
services/orchest-webserver/app/app/views/views.py

Covers job pipeline runs and some minor fixes.

Shift anonymization responsibility to analytics module callers, part 2

---

services/orchest-webserver/app/app/core/filemanager.py
services/orchest-webserver/app/app/utils.py
services/orchest-webserver/app/app/views/views.py
services/orchest-webserver/client/src/components/ParamTree.tsx
services/orchest-webserver/client/src/edit-job-view/EditJobView.tsx
services/orchest-webserver/client/src/edit-job-view/LoadParametersDialog.tsx
services/orchest-webserver/client/src/hooks/useCheckFileValidity.tsx
services/orchest-webserver/client/src/pipeline-settings-view/GenerateParametersDialog.tsx
services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
services/orchest-webserver/client/src/pipeline-view/PipelineStep.tsx
services/orchest-webserver/client/src/pipeline-view/PipelineView.tsx
services/orchest-webserver/client/src/pipeline-view/file-manager/FileManager.tsx
services/orchest-webserver/client/src/pipeline-view/file-manager/FileManagerContext.tsx
services/orchest-webserver/client/src/pipeline-view/file-manager/common.tsx
services/orchest-webserver/client/src/pipeline-view/step-details/StepDetailsContext.tsx

File Manager should read from the snapshot instead of the working directory when viewing a job run.

Fix file manager browsing on the read-only mode issue

---

docs/source/getting_started/installation.rst

Add system requirements to documentation to make them more explicit.

Add system requirements to documentation

---

services/auth-server/app/app/models.py
services/auth-server/app/app/views.py
services/auth-server/app/config.py
services/auth-server/app/migrations/versions/9376105c8654_.py
services/auth-server/app/migrations/versions/fe9a960dc117_.py

Description (including a screenshot/video if applicable) of what your PR solves or adds.
Fixes: #570

Support multiple client sessions per user

---

services/auth-server/client/src/views/Admin.tsx
services/orchest-webserver/client/src/views/ManageUsersView.tsx

Add a simple client-side validation to the add user form.

Apply client-side validation on the Add User form in auth-server

---

services/orchest-controller/pkg/utils/k8s_utils.go

Setting fqdn is currently broken, this PR will fix it
Fixes: #issue

do not insert the env var in to the map if it is already present.

---

docs/source/_static/css/installer_widget.css
docs/source/_static/js/installer_widget.js

The two-column design using flexbox and fixed width will require the `max-width` for the content container to be set. One-column design is more responsiveness-friendly, and doesn't significantly reduce the readability of the UI.

Change two-column design to one-column design.

---

docs/source/_static/js/installer_widget.js

add gke and eks installation instructions.
Fixes: #issue

add gke and eks installation instructions

---

services/orchest-webserver/client/src/views/JupyterLabView.tsx

It's a regression introduced in #1112. As a clean-up, the state `hasEnvironmentCheckCompleted` is removed.

fix: JupyterLab stuck when session already exists

---

docs/source/_static/css/custom_styles.css
docs/source/_static/css/rate_widget.css
docs/source/_static/js/installer_widget.js
docs/source/_static/js/rate_widget.js
docs/source/conf.py

This PR adds a "rate the docs" widget to the Orchest docs.
Demo: https://www.loom.com/share/12fb1437ab8c4c0fba100c29312c1c9c
Inspiration taken from:  https://github.com/medmunds/rate-the-docs. Thank you @medmunds!

Add rating widget, fix sidebar scrollbar issue.

---

lib/python/orchest-internals/_orchest/internals/config.py

I missed this commit from the previous PR #1123.

Add missed INGRESS_CLASS config

---

lib/javascript/utils/src/fetcher.ts
services/orchest-webserver/client/src/environments-view/common.tsx

Fixes an issue with failing to fetch sessions when trying to remove an environment.

Fix bad sessions URL

---

services/orchest-webserver/client/src/pipeline-view/file-manager/FileTree.tsx

Always cancel renames when canceling dialogs

---

docs/source/_static/js/rate_widget.js

Handle READTHEDOCS_DATA and don't pollute global namespace.

Fix Javascript errors in docs by correctly handling `READTHEDOCS_DATA`

---

docs/source/_static/js/rate_widget.js
docs/source/development/development_workflow.md
services/orchest-webserver/client/src/components/BuildPendingDialog.tsx
services/orchest-webserver/client/src/contexts/SessionsContext.tsx
services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx

Release `v2022.07.4`

---

services/orchest-webserver/client/src/pipeline-view/hooks/useAutoStartSession.tsx

Removes the error dialog shown in this video:
https://www.loom.com/share/cff42bbb98e64fa88660c281268fcc43

Fix error on environments page

---

.wci.yml

As per title. See https://workflows.community/systems/contribute

Add Workflows Community Initiative metadata

---

services/orchest-api/app/app/core/image_utils.py

Get exit code to avoid race condition on failure

---

services/orchest-controller/pkg/addons/helm_deployer.go

This PR only removes helm histories if the helm release is present.
Fixes: #issue

Only remove helm histories if there is already a helm release

---

services/orchest-webserver/app/app/core/projects.py

Fixes a recently introduced bug where "skip_env_builds" would cause the environment to not be registered in the `orchest-api`. The bug was introduced in https://github.com/orchest/orchest/commit/82d19ac7b3d94c9caa017a2371abed307d15d13d, the endpoint argument causing this error is currently only used internally.

Always post environment to `orchest-api` when creating a project

---

docs/source/getting_started/installation.md

Add instructions on setting up a reverse proxy, for example after installing Orchest in EC2.

Add instructions on setting up a reverse proxy

---

services/orchest-webserver/app/app/views/views.py
services/orchest-webserver/client/src/api/projects/projectsApi.ts
services/orchest-webserver/client/src/components/CommandPalette.tsx
services/orchest-webserver/client/src/projects-view/CreateProjectDialog.tsx
services/orchest-webserver/client/src/projects-view/ImportDialog.tsx
services/orchest-webserver/client/src/projects-view/ProjectList.tsx
services/orchest-webserver/client/src/projects-view/RenameProjectDialog.tsx
services/orchest-webserver/client/src/utils/webserver-utils.ts
services/orchest-webserver/client/src/views/ProjectSettingsView.tsx

This PR does what it says on the tin:

UI Overhaul: Add delete button on projects settings page

---

.dockerignore
services/orchest-controller/Dockerfile
services/orchest-controller/Makefile
services/orchest-controller/deploy/helm/templates/deployment.yaml
services/orchest-controller/deploy/helm/values.yaml

This PR passes the default version as a command line argument so that the controller rebuild would be fast.
Fixes: #989

Pass version as command line to controller

---

CONTRIBUTING.md

Just a link to our documentation, which should contain all the up-to-date information.
Fix gh-1139.

Add top-level CONTRIBUTING.md

---

services/orchest-controller/deploy/helm/templates/deployment.yaml

This PR passes the correct env vars to orchest-controller deployment.
Fixes: #issue

fix env in orchest-controller deployment helm chart

---

docs/source/_static/css/installer_widget.css
docs/source/conf.py
lib/python/orchest-internals/_orchest/internals/config.py

New Orchest release: `v2022.08.11`

Release `v2022.08.11`

---

services/orchest-api/app/app/__init__.py

This change allows to cleanup sessions left dangling due to unexpected errors, e.g. when the `k8s-api` isn't available or times out. Works in a retroactive way.

Shutdown dangling session during cleanup

---

services/orchest-webserver/app/app/core/projects.py
services/orchest-webserver/client/src/projects-view/CreateProjectDialog.tsx

Automatically create a Pipeline on Project creation (if applicable)

---

services/orchest-api/app/app/core/sessions/_core.py

Only create session sidecar if needed

---

services/orchest-api/app/app/utils.py

Fix settings DB records stating that a restart is required on install

---

services/orchest-webserver/client/src/pipeline-view/pipeline-logs-dialog/PipelineLogs.tsx
services/orchest-webserver/client/src/pipeline-view/pipeline-logs-dialog/common.tsx

This PR fixes the issue that some steps are sometimes missing in Pipeline > Logs.

fix: PipelineLogs should show all steps.

---

lib/python/orchest-internals/_orchest/internals/utils.py
services/orchest-webserver/app/app/utils.py
services/orchest-webserver/app/app/views/orchest_api.py
services/orchest-webserver/app/scripts/log_streamer.py

Clear step logs on interactive run request

---

services/orchest-webserver/client/src/pipeline-view/pipeline-canvas-header-bar/primary-action/PrimaryPipelineActionMenu.tsx
services/orchest-webserver/client/src/pipeline-view/pipeline-viewport/PipelineViewportContextMenu.tsx

Disable "run incoming" if there are no incoming

---

services/orchest-webserver/client/src/jobs-view/hooks/useScheduleJob.tsx

This just starts them immediately :shrug:

Allow scheduling jobs without a schedule

---

services/orchest-webserver/client/src/jobs-view/job-view/JobSummary.tsx

Cron string + humanized title to schedule

---

services/orchest-controller/pkg/controller/minikubereconciler/minikube_controller.go

Increases the readiness and liveness probes of the nginx ingress controller when the cluster is running in minikube. This is necessary for lowly specced instances which have high cpu contention to avoid the nginx pod restarting during times of cpu contention.

Alter ingress-nginx probes when deploying in minikube

---

services/orchest-webserver/app/app/__init__.py
services/orchest-webserver/app/app/config.py
services/orchest-webserver/app/app/consts.py
services/orchest-webserver/app/app/utils.py
services/orchest-webserver/app/app/views/views.py

Some things that I ran into whilst going over some code in the webserver.

Remove unused code

---

services/orchest-api/app/app/apis/namespace_jobs.py
services/orchest-api/app/app/core/scheduler.py

Fixes a race condition that could occur between the job scheduler and the cancellation of job.

Fix race condition between job scheduler and job cancellation

---

services/orchest-webserver/client/src/projects-view/ImportDialog.tsx

Fixes: [ORC-935](https://linear.app/orchest/issue/ORC-935/import-project-dialog-copy)

Change copy to "import complete" instead of "upload complete"

---

services/orchest-webserver/client/src/components/common/CodeMirror.tsx
services/orchest-webserver/client/src/environments-view/edit-environment/EnvironmentSetupScript.tsx

Fixes [ORC-931](https://linear.app/orchest/issue/ORC-931)

Indicate that the setup script can't be edited on build

---

services/orchest-api/app/app/apis/namespace_jobs.py

Fixes a database Sharelock deadlock that could happen when multiple threads attempted to update run ` UpdateJobPipelineRun` when signalling the end of a pipeline run of the same job, resulting in one of the two (or more) updates getting lost.

Fix UpdateJobPipelineRun deadlock

---

services/orchest-api/app/app/apis/namespace_jobs.py
services/orchest-api/app/app/core/tasks.py

Fixes an issue that would result in flaky behaviour under load due to some wrongfully shared db connections.

Dispose of existing celery db connections post fork

---

services/orchest-controller/pkg/controller/orchestcomponent/component_utils.go

Description (including a screenshot/video if applicable) of what your PR solves or adds.
Fixes: #1358

Set the `body-size` to `0` in ingress resources

---

cypress/cypress/integration/auth.spec.ts
cypress/cypress/integration/file-system-interactions.spec.ts
cypress/cypress/integration/interactive-runs.spec.ts
cypress/cypress/integration/jobs.spec.ts
cypress/cypress/integration/pipelines.spec.ts
cypress/cypress/integration/projects.spec.ts
cypress/cypress/integration/services.spec.ts
cypress/cypress/support/commands.ts
cypress/cypress/support/common.ts
services/orchest-webserver/client/src/header-bar/NavigationTabs.tsx
services/orchest-webserver/client/src/project-selector/GoToExamplesButton.tsx
services/orchest-webserver/client/src/project-selector/ProjectSelectorMenu.tsx
services/orchest-webserver/client/src/project-selector/ProjectSelectorToggle.tsx
services/orchest-webserver/client/src/projects-view/ProjectList.tsx

This PR ensures that Cypress is able to navigate the project using the new menu structure.
- Added needed data-test-id's
- Updated Cypress commands to support the new navigation structure

Cypress: Navigation

---

README.md
docs/source/development/development_workflow.md
services/orchest-webserver/client/src/contexts/ProjectsContext.tsx
services/orchest-webserver/client/src/projects-view/ProjectsTable.tsx

New Orchest release :raised_hands:

Release v2022.10.9

---

services/orchest-api/app/app/core/environment_image_builds.py

Do not assume non-root user in base env image

---

services/base-images/runnable-shared/runner/run.py
services/base-images/runnable-shared/runner/runner/runners.py

Log if a step file is not found during a run

---

services/orchest-webserver/client/src/pipeline-view/LogViewer.tsx

This PR fixes so that the "logs" output xterm is reflowed when its parent panel is resized.
https://user-images.githubusercontent.com/8259221/201374900-289718cb-cae6-43f5-a79d-7d6bd36410e0.mp4

Reflow step logs on resize panel

---

services/orchest-webserver/client/src/jupyter/Jupyter.tsx

JupyterLab is currently unusable on devices with a screen size smaller than 500 pixels.
This is because our current "did JupyterLab render OK?"-check is a bit naive.
This PR fixes that. :slightly_smiling_face:

Fix JupyterLab on mobile

---

lib/python/orchest-internals/_orchest/internals/compat.py
services/orchest-api/app/app/core/pipeline_runs.py
services/orchest-api/app/app/core/pod_scheduling.py
services/orchest-api/app/app/types.py
services/orchest-webserver/app/app/utils.py
services/orchest-webserver/client/src/pipeline-settings-view/PipelineSettingsView.tsx
services/orchest-webserver/client/src/types.d.ts
services/orchest-webserver/client/src/utils/pipeline-schema.ts

Adds a pipeline setting to limit parallelism at the step level, this allows to have finer control over said parallelism without having to alter the pipeline structure.

Add pipeline setting to limit step level parallelism

---

services/orchest-api/app/app/__init__.py

Hotfix release to fix an issue affecting new instances.

release v2023.01.1

---

services/orchest-controller/pkg/controller/orchestcomponent/rabbitmq_server.go

Fixes: fixes an issue that could lead to loss of state (pending runs/builds)  during a restart.

Pin rabbitmq hostname
